### ISSUE TITLE
Operation Expired when streaming data from SE

### ISSUE THREAD

**Issue by rajanandakumar** [xrootd/xrootd#1259]
Dear xrootd experts,

We have an issue seen by LHCb at the RAL Tier-1 over the last year or so and we are trying to understand and solve it. The issue is as follows - when a LHCb job tries to stream data off the RAL ECHO storage, it fails every once in a while leading to eventual job failures of ~ 20% or more depending on the number of input files being processed. This can become an issue especially for user jobs.

Following a controlled study (which we can tweak as needed - feel free to suggest!) we see about 80% of the failures contain an "Operation expired" error as below. We have set XRD_LOGLEVEL=Dump to get the output below and in this particular case the input file is about 5GB in size (root://xrootd.echo.stfc.ac.uk:1094/lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst).

Any suggestions on what to do to fix / understand the problem would be greatly appreciated! We have so far tried to set XRD_STREAMTIMEOUT=600 but that has not helped.

```
[2020-07-22 06:51:04.479831 +0000][Dump   ][TaskMgr           ] Will rerun task "FileTimer task" at [2020-07-22 06:51:19 +0000]
[2020-07-22 06:51:15.046797 +0000][Dump   ][XRootDTransport   ] [xrootd.echo.stfc.ac.uk:1094 #0.0] Stream inactive since 392 seconds, TTL: 300, allocated SIDs: 4, open files: 4
[2020-07-22 06:51:15.046842 +0000][Dump   ][XRootDTransport   ] [xrootd.echo.stfc.ac.uk:1094 #0.0] Stream inactive since 392 seconds, stream timeout: 600, allocated SIDs: 4, wait barrier: 2020-07-22 06:44:43 +00
00
[2020-07-22 06:51:18.481068 +0000][Dump   ][TaskMgr           ] Running task: "TickGeneratorTask for: xrootd.echo.stfc.ac.uk:1094"
[2020-07-22 06:51:18.481119 +0000][Dump   ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Stream event reported for msg kXR_readv (handle: 0x03000000, chunks: 1024, total size: 1709338)
[2020-07-22 06:51:18.481135 +0000][Debug  ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Handling error while processing kXR_readv (handle: 0x03000000, chunks: 1024, total size: 1709338): [ERROR] Operation 
expired.
[2020-07-22 06:51:18.481145 +0000][Error  ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Unable to get the response to request kXR_readv (handle: 0x03000000, chunks: 1024, total size: 1709338)
[2020-07-22 06:51:18.481171 +0000][Dump   ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Stream event reported for msg kXR_readv (handle: 0x03000000, chunks: 230, total size: 394117)
[2020-07-22 06:51:18.481183 +0000][Debug  ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Handling error while processing kXR_readv (handle: 0x03000000, chunks: 230, total size: 394117): [ERROR] Operation ex
pired.
```

I also note that this issue is fairly random
* The file itself is fine.
* After enough retries the job finally processes the file
* It helps to have as few files as possible (which is painful when you are dealing with ~20K input files!)
* The failure happens randomly in the file - not always at the beginning (or the end). Sometimes the job can run for hours before failing.
* The same file can be processed successfully by another job on the same machine
* The issue seemingly affects any file when streaming through xrootd.
* Though the issue is seen occasionally at other sites, the failure rate at RAL is much much higher than all other sites combined.

Also the xrootd client used is version 4.11.2 (and I believe the server is the same or very close).

**Comment by bbockelm** [comment]
Hi @rajanandakumar -

"Operation expired" simply means a timeout occurred before the xrootd server returned a response for a given operation (in this case, a vector read).  In other words, the server didn't respond fast enough -- which can happen randomly, of course, as you may not know how busy the remote server is.

Unfortunately, this is possibly a side-effect of how RAL deploys its storage.  IIRC (and do check up with them, my memory may be dated) the backend storage requires a minimum of X MB to be read (perhaps X=32?) for XRootD to service a read.  So, vector read requests with many small reads may require up to the full file to be read out in one operation.

That is, if your read of 1024 chunks noted above is perfectly scattered throughout the file, then the backend may need to read out up to 5GB within the operation timeout to service the 1.7MB request.

RAL has historically addressed this through a caching layer - but that can be finicky to tune as large files can effectively permanently thrash the cache.

It's not clear that this is something that the XRootD team can solve.  It might make sense to strike up a conversation with RAL - I know they've been studying this closely and may have some updates that invalidates my recollections above.

Brian

**Comment by wyang007** [comment]
IFAIK, X=64.

Yes, RAL has a cache in the front to handle the load. But If I am not mistaken, the cache resides on RAL batch nodes and only will only serve the RAL batch nodes. So Raja, where are your streaming jobs running?

As Brian mentioned, even with a cache, the cache thrashing can still happens if the cache size is not big enough. In any case, it is best to start a discussion with RAL. I think RAL fully understand the usefulness of the cache.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 7/22/20, 7:30 AM, "Brian P Bockelman" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @rajanandakumar<https://github.com/rajanandakumar> -

"Operation expired" simply means a timeout occurred before the xrootd server returned a response for a given operation (in this case, a vector read). In other words, the server didn't respond fast enough -- which can happen randomly, of course, as you may not know how busy the remote server is.

Unfortunately, this is possibly a side-effect of how RAL deploys its storage. IIRC (and do check up with them, my memory may be dated) the backend storage requires a minimum of X MB to be read (perhaps X=32?) for XRootD to service a read. So, vector read requests with many small reads may require up to the full file to be read out in one operation.

That is, if your read of 1024 chunks noted above is perfectly scattered throughout the file, then the backend may need to read out up to 5GB within the operation timeout to service the 1.7MB request.

RAL has historically addressed this through a caching layer - but that can be finicky to tune as large files can effectively permanently thrash the cache.

It's not clear that this is something that the XRootD team can solve. It might make sense to strike up a conversation with RAL - I know they've been studying this closely and may have some updates that invalidates my recollections above.

Brian

**Comment by rajanandakumar** [comment]
Dear @bbockelm and @wyang007 

Many thanks for your responses. To start with, I am the RAL contact who is looking at this with support from the ECHO team. My expertise is more in the field of some of the LHCb software, though I will be happy to feed back suggestions or include the relevant RAL administrators in this discussion as needed. Unfortunately there is not much expertise on xrootd within RAL and so we need help from you in solving this issue!

To answer @wyang007 my jobs are running within RAL on dedicated worker nodes which replicate the production setup. But these machines run only test jobs and we can tweak the settings here to see if the issue gets fixed. The cache size is a few 100 GB in size. We have this test system because LHCb have observed this issue on a large scale and we are trying to solve it.

@bbockelm For my understanding, why doesn't xrootd reopen the file? We see quite a few "socket errors" in general but this is never (apparently) fatal. The socket closes and then reopens. What happens that this process is terminated in such cases? For example, we see

```
[2020-07-22 20:42:20.822408 +0000][Error  ][AsyncSock         ] [xrootd.echo.stfc.ac.uk:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout
[2020-07-22 20:42:20.822418 +0000][Debug  ][AsyncSock         ] [xrootd.echo.stfc.ac.uk:1094 #0.0] Closing the socket
[2020-07-22 20:42:20.822431 +0000][Debug  ][Poller            ] <[::ffff:172.28.5.33]:60726><--><[::ffff:172.28.1.1]:1094> Removing socket from the poller
[2020-07-22 20:42:20.822510 +0000][Error  ][PostMaster        ] [xrootd.echo.stfc.ac.uk:1094 #0] elapsed = 108, pConnectionWindow = 120 seconds.
[2020-07-22 20:42:20.822532 +0000][Info   ][PostMaster        ] [xrootd.echo.stfc.ac.uk:1094 #0] Attempting reconnection in 12 seconds.
[2020-07-22 20:42:20.822546 +0000][Debug  ][TaskMgr           ] Registering task: "StreamConnectorTask for xrootd.echo.stfc.ac.uk:1094 #0" to be run at: [2020-07-22 20:
42:32 +0000]
[2020-07-22 20:42:26.822614 +0000][Dump   ][TaskMgr           ] Running task: "FileTimer task"
[2020-07-22 20:42:26.822672 +0000][Dump   ][File              ] [0x2ce62820@root://xrootd.echo.stfc.ac.uk:1094/lhcb:prod/lhcb/LHCb/Collision16/FULLTURBO.DST/00052099/00
00/00052099_00001653_2.fullturbo.dst] Got a timer event
```

The file reads are in general not random I suppose - in normal operations we would read from the beginning to the end of the file, looping over the events and my test jobs do exactly that.

I am not sure that I understand why the streaming should essentially do a copy locally of the whole file at one go. Doesn't this negate the whole point of the streaming? Apologies if this has been discussed before, but I am not completely aware of the detailed rationale behind the choices of the system, except in a general sense.

It would be ideal if this problem can be made to "go away" by fine tuning the caching layer. For this, it would be nice to have a feel for what variables will affect the caching layer - it would be great if you could point us in that direction. Of course we will be happy to consider other solutions if that is the best way forward. It is clear however that the current situation cannot be the status quo.

Many thanks and Cheers,
Raja.

**Comment by wyang007** [comment]
Hi Raja,

Can you clarify whether your batch jobs read from Xcache or not? If so,  how does the Xcache setup? In addition to cache size, one important parameter in Xcache is “pfc.blocksize”. You may want to set it to something large, like 64MB (close or equal to CEPH data block size). For explanation of “pfc.blocksize”, see https://xrootd.slac.stanford.edu/doc/dev50/pss_config.htm#_Toc42114746.

If LHCb uses root data format, then the data reading is not sequential. Without a cache, or if the cache keeps on thrashing data (because the size is too small), then adjacent reads will cause CEPH to delivery the same data block multiple times. Think of the following scenario:

read(offset=0, len=10)
read(offset=11, len=10)

Without a cache, CEPH will fetch the first 64MB data for the first read, and then fetch the same 64MB again for the second read. The frontend cache will smooth out these, so CEPH will only need to deliver the 64MB block once.

If I have to guess, the rest of the issue you reported are likely related to xrootd being overwhelmed.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 7/22/20, 2:59 PM, "Raja Nandakumar" <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @bbockelm<https://github.com/bbockelm> and @wyang007<https://github.com/wyang007>

Many thanks for your responses. To start with, I am the RAL contact who is looking at this with support from the ECHO team. My expertise is more in the field of some of the LHCb software, though I will be happy to feed back suggestions or include the relevant RAL administrators in this discussion as needed. Unfortunately there is not much expertise on xrootd within RAL and so we need help from you in solving this issue!

To answer @wyang007<https://github.com/wyang007> my jobs are running within RAL on dedicated worker nodes which replicate the production setup. But these machines run only test jobs and we can tweak the settings here to see if the issue gets fixed. The cache size is a few 100 GB in size. We have this test system because LHCb have observed this issue on a large scale and we are trying to solve it.

@bbockelm<https://github.com/bbockelm> For my understanding, why doesn't xrootd reopen the file? We see quite a few "socket errors" in general but this is never (apparently) fatal. The socket closes and then reopens. What happens that this process is terminated in such cases? For example, we see

[2020-07-22 20:42:20.822408 +0000][Error  ][AsyncSock         ] [xrootd.echo.stfc.ac.uk:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout

[2020-07-22 20:42:20.822418 +0000][Debug  ][AsyncSock         ] [xrootd.echo.stfc.ac.uk:1094 #0.0] Closing the socket

[2020-07-22 20:42:20.822431 +0000][Debug  ][Poller            ] <[::ffff:172.28.5.33]:60726><--><[::ffff:172.28.1.1]:1094> Removing socket from the poller

[2020-07-22 20:42:20.822510 +0000][Error  ][PostMaster        ] [xrootd.echo.stfc.ac.uk:1094 #0] elapsed = 108, pConnectionWindow = 120 seconds.

[2020-07-22 20:42:20.822532 +0000][Info   ][PostMaster        ] [xrootd.echo.stfc.ac.uk:1094 #0] Attempting reconnection in 12 seconds.

[2020-07-22 20:42:20.822546 +0000][Debug  ][TaskMgr           ] Registering task: "StreamConnectorTask for xrootd.echo.stfc.ac.uk:1094 #0" to be run at: [2020-07-22 20:

42:32 +0000]

[2020-07-22 20:42:26.822614 +0000][Dump   ][TaskMgr           ] Running task: "FileTimer task"

[2020-07-22 20:42:26.822672 +0000][Dump   ][File              ] [0x2ce62820@root://xrootd.echo.stfc.ac.uk:1094/lhcb:prod/lhcb/LHCb/Collision16/FULLTURBO.DST/00052099/00

00/00052099_00001653_2.fullturbo.dst] Got a timer event

The file reads are in general not random I suppose - in normal operations we would read from the beginning to the end of the file, looping over the events and my test jobs do exactly that.

I am not sure that I understand why the streaming should essentially do a copy locally of the whole file at one go. Doesn't this negate the whole point of the streaming? Apologies if this has been discussed before, but I am not completely aware of the detailed rationale behind the choices of the system, except in a general sense.

It would be ideal if this problem can be made to "go away" by fine tuning the caching layer. For this, it would be nice to have a feel for what variables will affect the caching layer - it would be great if you could point us in that direction. Of course we will be happy to consider other solutions if that is the best way forward. It is clear however that the current situation cannot be the status quo.

Many thanks and Cheers,
Raja.

**Comment by xrootd-dev** [comment]
Actually, it could very well be that Ceph is being overwhelmed. If indeed, 
Ceph is being asked to refetch the 64MB block each time, Ceph will 
definitely melt down and an operation expired will be the result, 
gauranteed.

Andy

**Comment by rajanandakumar** [comment]
@wyang007 Yes - the jobs read from the xcache. Looking at the configuration I see the following in the xrootd config on the worker node

```
pfc.ram 7g
pfc.diskusage 0.89 0.90 purgecoldfiles 2d 5
pfc.blocksize 16m
```
Actually we have two configuration files - for the gateway and the proxy. Would it make sense to post both of them here for you to have a look?

@xrootd-dev  and @wyang007  Both of you mentioned CEPH being overwhelmed. Is there anything else (other than the "Operation expired" error) that xrootd would expect that I can see on the storage side? From what I understand the storage admins at RAL see that CEPH is healthy from the point of view of the storage.

Thanks and Cheers,
Raja.

**Comment by wyang007** [comment]
Hi Raja,

You can send those config files directly to me (yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>) and Andy (abh@slac.stanford.edu<mailto:abh@slac.stanford.edu>). I think it is best not to post those config files on the internet.

I though RAL has a cluster of Xcache setup on batch nodes. Or do you only have one machine for Xcache? If so, how much space does Xcache has?

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 7/22/20, 3:51 PM, "Raja Nandakumar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@wyang007<https://github.com/wyang007> Yes - the jobs read from the xcache. Looking at the configuration I see the following in the xrootd config on the worker node

pfc.ram 7g

pfc.diskusage 0.89 0.90 purgecoldfiles 2d 5

pfc.blocksize 16m

Actually we have two configuration files - for the gateway and the proxy. Would it make sense to post both of them here for you to have a look?

@xrootd-dev<https://github.com/xrootd-dev> and @wyang007<https://github.com/wyang007> Both of you mentioned CEPH being overwhelmed. Is there anything else (other than the "Operation expired" error) that xrootd would expect that I can see on the storage side? From what I understand the storage admins at RAL see that CEPH is healthy from the point of view of the storage.

Thanks and Cheers,
Raja.

**Comment by xrootd-dev** [comment]
There wouldn't be any other indication of a Ceph isue except a timeout. 
The timeout interval defaults to 30 minutes so something is really amiss 
(this assumes the value has not been changed via config or envar). Now, 
was the log snippet that showed the request timeout for an application for 
from the Xcache server? If the former, it would help to see the actual 
Xcache log file. Now, yes, the config files for both would be helpful. Do 
you know what the intrinsic block size is for RAL's Ceph? I thought it was 
64MB but I may very well be wrong.

Andy

**Comment by rajanandakumar** [comment]
@wyang007 and @xrootd-dev  Thanks. I am sending the config files to you.

@xrootd-dev  I will ask what the block size is. About the timeout, hopefully the two config files will help - I don't think anything else is changed from the default.

@wyang007 If I understood your question correctly, every worker node has a container running permanently with the proxy cache and all the jobs on the WN connect to this container to access the input file. The proxy container in turn talks to another (local) container which runs the xrootd gateway service which directly talks to the disk server.

Cheers,
Raja.

**Comment by rajanandakumar** [comment]
@xrootd-dev Confirmed - the block size for CEPH @ RAL is 64MB as you thought!

Cheers,
Raja.

**Comment by bbockelm** [comment]
> From what I understand the storage admins at RAL see that CEPH is healthy from the point of view of the storage.

Right.  Ceph can be perfectly healthy and performant and still not be fast enough to beat the request timeout.  One thing you can monitor for is the ratio of data in / out of the cache process -- you can likely see this impact when there's much greater data in than out.

It's not clear from your above debug statements _when_ the timeout is hitting.  Andy mentioned that the internal default is 30 minutes -- but there are several ways this can get overridden (CMS does this, for example).

> For my understanding, why doesn't xrootd reopen the file? We see quite a few "socket errors" in general but this is never (apparently) fatal.

There's a complex set of retry rules for recovery from errors; I'm not an expert on them.  However, in general, if a server is overloaded and you retry then you just end up with a more-overloaded server.  It's not clear to me that retrying on timeouts is an obvious strategy.

> The file reads are in general not random I suppose - in normal operations we would read from the beginning to the end of the file, looping over the events and my test jobs do exactly that

Unfortunately, this really depends on the LHCb files themselves.  In CMS, for example, some of the metadata read up front is scattered throughout the file -- it might only be a few MB of data in total but works maximally poorly with caching strategies.  I believe you can get the Xrootd client or server to log each specific offset in a vectored read to see what ROOT is trying to do.

**Comment by wyang007** [comment]
Just to put a comment here since Raja, Andy and I are using another e-mail thread for discussion because it potentially involves site detailed configuration.

What I see from those configs is that the CEPH block site is 64M (as Raja confirmed), but the CEPH-xrootd gateway using 16M for async IO. The Xcache use 64M for async IO and 16M for pfc.blocksize. So I am suggesting Raja to change all of them to 64M.

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

**Comment by abh3** [comment]
Indeed, if the async blocksize if 16M then the proxy will send out 4 reads 
of 16M at once which, unfortuantely, will stress Ceph out. It should send 
one of 64M then Ceph will be doing the smallest amount of work per read.

Andy

**Comment by Tom-Byrne** [comment]
I've extracted the respective server log file for the Xcache and Ceph gateway for the job log snippet in Raja's first post. I've had to clean this up fairly heavily as it all ends up in /var/log/messages, but I think I've got the relevant bits. The timeout in the original post happened at 7:51:18 in this log.

I don't think there is anything particularly suspicious, although I may be missing something.

Next I'm going to try harmonising the block sizes between the Xcache and the gateway (to 64MB), and I'm going to turn on the relevant xrootd tracing setting so we can see what vector reads the servers are trying to carry out when these errors occur. I'll also look into whether Xcache can report any cache efficiency stats, I know the memory proxy has an option to log various cache stats, but I looked for anything similar for Xcache.

> Jul 22 07:44:43 lcg2160 docker: 200722 06:44:43 6232 acc_Audit: tlhcb008.213:77@htcjob6575500_0_slot1_33_pid36209.ralworker grant gsi lhcbprod@htcjob6575500_0_slot1_33_pid36209.ralworker read lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DS
> T/00046157/0000/00046157_00001735_1.allturbo.dst
> Jul 22 07:46:42 lcg2160 docker: 200722 06:46:42 4201 XrootdXeq: u41.7:4284@localhost pvt IP46 login as xrootd
> Jul 22 07:46:45 lcg2160 docker: 200722 06:46:45 4990 XrdLink: Unable to send to u41.7:4307@localhost; broken pipe
> Jul 22 07:46:45 lcg2160 docker: 200722 06:46:45 4990 XrootdXeq: u41.7:4307@localhost disc 0:03:10 (send failure)
> Jul 22 07:46:45 lcg2160 docker: ceph_close: closed fd 7407 for file prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst, read ops count 1377, write ops count 0
> Jul 22 07:46:46 lcg2160 docker: ceph_open: fd 7420 associated to lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst
> Jul 22 07:47:46 lcg2160 docker: 200722 06:47:46 4900 XrootdXeq: u41.7:4322@localhost pvt IP46 login as xrootd
> Jul 22 07:47:48 lcg2160 docker: 200722 06:47:48 706 XrdLink: Unable to send to u41.7:4284@localhost; broken pipe
> Jul 22 07:47:48 lcg2160 docker: 200722 06:47:48 706 XrootdXeq: u41.7:4284@localhost disc 0:01:06 (send failure)
> Jul 22 07:47:48 lcg2160 docker: ceph_close: closed fd 7420 for file prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst, read ops count 459, write ops count 0
> Jul 22 07:47:50 lcg2160 docker: ceph_open: fd 7424 associated to lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst
> Jul 22 07:48:50 lcg2160 docker: 200722 06:48:50 3824 XrootdXeq: u41.7:4298@localhost pvt IP46 login as xrootd
> Jul 22 07:48:54 lcg2160 docker: 200722 06:48:54 5641 XrdLink: Unable to send to u41.7:4322@localhost; broken pipe
> Jul 22 07:48:54 lcg2160 docker: 200722 06:48:54 5641 XrootdXeq: u41.7:4322@localhost disc 0:01:08 (send failure)
> Jul 22 07:48:54 lcg2160 docker: ceph_close: closed fd 7424 for file prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst, read ops count 459, write ops count 0
> Jul 22 07:49:00 lcg2160 docker: ceph_open: fd 7430 associated to lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst
> Jul 22 07:50:00 lcg2160 docker: 200722 06:50:00 4201 XrootdXeq: u41.7:4308@localhost pvt IP46 login as xrootd
> Jul 22 07:50:08 lcg2160 docker: 200722 06:50:08 4811 XrdLink: Unable to send to u41.7:4298@localhost; broken pipe
> Jul 22 07:50:08 lcg2160 docker: 200722 06:50:08 4811 XrootdXeq: u41.7:4298@localhost disc 0:01:18 (send failure)
> Jul 22 07:50:08 lcg2160 docker: ceph_close: closed fd 7430 for file prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst, read ops count 459, write ops count 0
> Jul 22 07:50:10 lcg2160 docker: ceph_open: fd 7434 associated to lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst
> Jul 22 07:51:10 lcg2160 docker: 200722 06:51:10 4816 XrootdXeq: u41.7:4307@localhost pvt IP46 login as xrootd
> Jul 22 07:51:14 lcg2160 docker: 200722 06:51:14 4146 XrdLink: Unable to send to u41.7:4308@localhost; broken pipe
> Jul 22 07:51:14 lcg2160 docker: 200722 06:51:14 4146 XrootdXeq: u41.7:4308@localhost disc 0:01:14 (send failure)
> Jul 22 07:51:14 lcg2160 docker: ceph_close: closed fd 7434 for file prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst, read ops count 459, write ops count 0
> Jul 22 07:51:20 lcg2160 docker: ceph_open: fd 7437 associated to lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst
> Jul 22 07:52:20 lcg2160 docker: 200722 06:52:20 4885 XrootdXeq: u41.7:4315@localhost pvt IP46 login as xrootd
> Jul 22 07:52:26 lcg2160 docker: 200722 06:52:26 5641 XrdLink: Unable to send to u41.7:4307@localhost; broken pipe
> Jul 22 07:52:26 lcg2160 docker: 200722 06:52:26 5641 XrootdXeq: u41.7:4307@localhost disc 0:01:16 (send failure)
> Jul 22 07:52:26 lcg2160 docker: ceph_close: closed fd 7437 for file prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst, read ops count 459, write ops count 0
> Jul 22 07:52:30 lcg2160 docker: ceph_open: fd 7442 associated to lhcb:prod/lhcb/LHCb/Collision15em/ALLTURBO.DST/00046157/0000/00046157_00001735_1.allturbo.dst

**Comment by osschar** [comment]
> There wouldn't be any other indication of a Ceph isue except a timeout. The timeout interval defaults to 30 minutes so something is really amiss (this assumes the value has not been changed via config or envar). 

For pss the remote request timeout is actually lower, 300 s.
https://xrootd.slac.stanford.edu/doc/dev50/pss_config.htm#_Toc42114745

**Comment by abh3** [comment]
Currently, there is no way to get cache statistics in the 4.x series. 
Limited statistics can be generated in the 5.x series. However, you will 
need to wait for a patch release to run the 5.x series with Xcache.

**Comment by rajanandakumar** [comment]
As a quick update, we had a quattor issue over the weekend due to which the changes did not get picked up by the test worker nodes. Hopefully it is fixed now and we will have some more information for you on Wednesday.

Formally speaking looking at CEPH, I understand that taking all delays into account, the maximum time lag of a request coming in from the gateway container on the worker node, and the response from echo is < 5 seconds. Certainly a lot less than 30 minutes. Hopefully the tracing that Tom is getting will give us what is the timeout that is being hit here.

About the 5.x series, what statistics will we be getting (of interest in this discussion)? And what timescale are we looking at for this?

**Comment by bbockelm** [comment]
> the maximum time lag of a request coming in from the gateway container on the worker node, and the response from echo is < 5 seconds. Certainly a lot less than 30 minutes

One thing that you might have overlooked was an earlier request for logs when you see an operation timeout.  What you posted above is only the "timeout" piece but it's not apparent _when_ the request started (was truncated).

That said, there is something slightly funny in the server messages you post:

> Jul 22 07:51:14 lcg2160 docker: 200722 06:51:14 4146 XrdLink: Unable to send to u41.7:4308@localhost; broken pipe

@abh3 - shouldn't the client be shutting down the connection cleanly?  Seems strange it just would end like that... similarly, it's strange that each file processed is a separate connection (the Xrootd client aggressively reuses sessions).

**Comment by abh3** [comment]
The client might be shutting down cleanly but we won't know that when the 
socket is disabled from presenting interrupts to avoid dealing with 
chatter. So, when the server decides to write to the socket while it's 
masked it will get a broken pipe error. So, it's a perfectly normal code 
path.

Andy

  . The server does that to 
improve 
performance. So,

**Comment by rajanandakumar** [comment]
Hi,

As an update, over many days  there has not been any change in the rate of successful jobs with the block sizes at 64MB as suggested by @wyang007 .

I note though that the changes were applied only on the test WNs. However, we see CEPH as performing normally. So it is not clear to me if there is a reason to apply it to the whole batch farm to see an effect.

@Tom-Byrne  is waiting for the CE to come back after upgrading to get the tracing with timestamp information for a running job.

Regards,
Raja.

**Comment by bbockelm** [comment]
@rajanandakumar - to go back to the comment from last week, can you post a full debug session from the client including when the request is made?  Still not clear to me when things are timing out...

**Comment by rajanandakumar** [comment]
Hi @bbockelm 

If you are referring to the log from the job, do let me know and I can post one. 

In case of the xrootd container, it is on the todo list of @Tom-Byrne hopefully by Friday. 

Regards 
Raja

**Comment by bbockelm** [comment]
> If you are referring to the log from the job, do let me know and I can post one (or as many as you want).

Yup - that's what I'm looking for.  Basically, the same as your first post but with a few more prior lines so we can see the timestamp when the operation was submitted.

**Comment by rajanandakumar** [comment]
Hi @bbockelm 

Apologies for the delay. The files are a bit large to copy-paste. So, I have uploaded two of the log files at the following links

http://lhcb-project-dirac.web.cern.ch/lhcb-project-dirac/2020-08-02_1532028_lcg2197_Script3_test_bender2.sh.log
http://lhcb-project-dirac.web.cern.ch/lhcb-project-dirac/2020-08-02_1532035_lcg2197_Script3_test_bender2.sh.log

Do let me know any comments (and if you are able to access them).

Kind Regards,
Raja.

**Comment by bbockelm** [comment]
@rajanandakumar - perfect, here are the two lines that I was looking for:
```
[2020-08-02 08:56:08.987640 +0000][Dump   ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Message kXR_readv (handle: 0x00000000, chunks: 627, total size: 9057777) has been successfully sent.
...
[2020-08-02 09:02:01.021140 +0000][Dump   ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Stream event reported for msg kXR_readv (handle: 0x00000000, chunks: 627, total size: 9057777)
[2020-08-02 09:02:01.021152 +0000][Debug  ][XRootD            ] [xrootd.echo.stfc.ac.uk:1094] Handling error while processing kXR_readv (handle: 0x00000000, chunks: 627, total size: 9057777): [ERROR] Operation expired.
```

So, it looks like the timeout is set to something in the neighborhood of 350 seconds.

To me, it's a bit more plausible to be hitting "real" timeouts at 350 seconds than 1,800 seconds (30 minutes)!

**Comment by osschar** [comment]
300 s is the XrdCl request timeout when used from pss

**Comment by abh3** [comment]
Yes, and that is adjustable, of course. The question is what would be a 
better value?

**Comment by bbockelm** [comment]
Ah - so @osschar are you suggesting that the 'operation expired' is coming from `xrootd.echo.stfc.ac.uk` as opposed to being able to generated internally by the client?

(To be clear, the logs from Raja are from the LHCb physics application).

Also @osschar - does that version of the proxy cache unwrap the vector reads into individual read operations?  Or does it keep it vectored?

**Comment by osschar** [comment]
Yes, that would be my guess, that proxy doesn't get the response from the remote / ceph.

If cache has the memory, it will unravel the vread request and request all the cache blocks it needs and issue each read request independently. Once it's out of memory, it will simply forward the vread as it got it.

I could send multiple block-reads as vread ... but Andy told me that from some block size (O(16 kB)?)
onwards that doesn't matter much.

I am, however, a little mortified over the 64 MB block size people were recommending here. If vector reads are used I usually tell people to rather go down to 32 kB :)

During the last Lyon workshop Andreas Peters said that the big problem with the ceph ofs interface is that it internally serializes the vread requests and handles them sequentially. I don't know how this applies here if cache already unravels the vreads.

Is lhcb usage similar to what we do in cmssw, i.e., vread baskets for all activated branches?

**Comment by bbockelm** [comment]
> Yes, that would be my guess, that proxy doesn't get the response from the remote / ceph.

Great!  That's a concrete thing that Raja and Chris can try.

@osschar - is the syntax to enable the `Debug` or `Dump` level in the XrdCl this:

```
pss.setopt DebugLevel 3
```

?

Specifically, it sounds like there are two very distinct code paths (unwrap or pass through) that the cache may be taking.  I'd be curious if one is particularly associated with an issue.

For example, if the "pass through" codepath is used then the change to the block size has no effect, potentially explaining what @rajanandakumar is seeing.

**Comment by osschar** [comment]
Yes:`
# To debug connections to the fedration (4 Debug, 3 Error, 2 Warning, 1 Info)
# This is extremely HEAVY and will slow down normal operation significantly
# and fill up your disk, too.
# **** Enable only when it is really needed!!! ****
# pss.setopt   DebugLevel 3`

Above it said they use pfc.ram 7G ... 7G/64M = 112 ... so they only have space for 112 blocks in RAM. So, if the vread comes into an indle cache, only first 112 blocks will be requested individually and cached, the rest will be issued as a single remote vread. Under any kind of load, I'd expect the cache to be firmly in a pass-through (i.e., no-cache) mode.

Has anybody tested access to ceph via xrootd independently (i.e, without cache) to see the read rates it can do for plain reads and vreads of relevant sizes?

**Comment by abh3** [comment]
Presumably, the log snippet Brian pointer to is the cache client issuing 
the read to Ceph at xrootd.echo.stfc.ac.uk:1094, right? So, it would 
appear the client is requesting 627 reads each averaging about 14K and 
each at a different offset. If xrootd.echo.stfc.ac.uk is not a caching 
server then that would represent a request for roughly 39GB (yes 
gigabytes) of data of which only 9MB would be extracted and sent back. 
Frankly, I don't see how Ceph could possibly complete the request in 300 
seconds unless there was almost no load on it. So, is 
xrootd.echo.stfc.ac.uk a caching gateway?

Note that Ceph does not support readv() so it has to unroll the vector 
read and issue each read individually. I suppose it could have been 
more clever and coalesced the reads that happen to be in the same 64MB 
page but that was not how it was written.

Andy

**Comment by wyang007** [comment]
Keep in mind that RAL manipulate /etc/hosts, so xrootd.echo.stfc.ac.uk is actually the batch node itself.

They run all (batch job/client, xcache (xrootd.echo.stfc.ac.uk), and ceph-xrootd) all on the same batch node (in container).

regards,
--
Wei Yang  |  yangw@slac.stanford.edu<mailto:yangw@slac.stanford.edu>  |  650-926-3338(O)

On 8/7/20, 12:54 PM, "Andrew Hanushevsky" <notifications@github.com<mailto:notifications@github.com>> wrote:

Presumably, the log snippet Brian pointer to is the cache client issuing
the read to Ceph at xrootd.echo.stfc.ac.uk:1094, right? So, it would
appear the client is requesting 627 reads each averaging about 14K and
each at a different offset. If xrootd.echo.stfc.ac.uk is not a caching
server then that would represent a request for roughly 39GB (yes
gigabytes) of data of which only 9MB would be extracted and sent back.
Frankly, I don't see how Ceph could possibly complete the request in 300
seconds unless there was almost no load on it. So, is
xrootd.echo.stfc.ac.uk a caching gateway?

Note that Ceph does not support readv() so it has to unroll the vector
read and issue each read individually. I suppose it could have been
more clever and coalesced the reads that happen to be in the same 64MB
page but that was not how it was written.

Andy

**Comment by abh3** [comment]
I would then say it doesn't really matter. The cache on that batch node 
probably passed through the readv as well with dire consequences.

**Comment by bbockelm** [comment]
> Presumably, log snippet Brian pointer to is the cache client issuing the read to Ceph at xrootd.echo.stfc.ac.uk:1094, right?

Nope!  That is from the physics application (i.e., ROOT).

**Comment by abh3** [comment]
Ah, OK. Then all we need to see if the readv() was passed through or not.

**Comment by bbockelm** [comment]
> Ah, OK. Then all we need to see if the readv() was passed through or not.

Indeed!  From earlier in the thread I wrote:

> Right. Ceph can be perfectly healthy and performant and still not be fast enough to beat the request timeout. One thing you can monitor for is the ratio of data in / out of the cache process -- you can likely see this impact when there's much greater data in than out.

I still think this is a good thing to examine.  It should be extremely obvious from Ganglia / Zabbix / your-favorite-host-monitoring-software whether 9 megabytes or 39 *giga*bytes is being sent to the host.

@osschar - to confirm, when the "pass through" logic is triggered, nothing goes into the cache, right?

**Comment by osschar** [comment]
look at my post above ... pfc.ram allows for only 112 blocks of 64M ... so majority of the request was forwarded as vread.

**Comment by osschar** [comment]
just the first 112 blocks.

**Comment by Tom-Byrne** [comment]
Hi all,

Tracing one 'operation expired' failure with tracing turned up, I got the following.

Client:

```
[2020-08-10 07:25:02.640039 +0000][Dump][XRootD] [xrootd.echo.stfc.ac.uk:1094] Message kXR_readv (handle: 0x00000000, chunks: 837, total size: 9403078) has been successfully sent.
...
[2020-08-10 07:30:58.618908 +0000][Debug][ExDbgMsg] [xrootd.echo.stfc.ac.uk:1094] Calling MsgHandler: 0x5c001300 (message: kXR_readv (handle: 0x00000000, chunks: 837, total size: 9403078) ) with status: [ERROR] Operation expired.
```

XCache:

```
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0100 open r lhcb:prod/lhcb/LHCb/Collision15/TURBO.MDST/00051290/0002/00051290_00025876_1.turbo.mdst
200810 07:25:02 7314 acc_Audit: tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker grant gsi lhcbprod@htcjob47005_0_slot1_23_pid30299.ralworker read lhcb:prod/lhcb/LHCb/Collision15/TURBO.MDST/00051290/0002/000
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdResponse: 0100 sending 4 data bytes
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 req=readv dlen=13392
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 fh=0 readV 674@71780326
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 fh=0 readV 356@71782997
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 fh=0 readV 813@71783601
==== ~800 readVs snipped ====
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 fh=0 readV 29117@105144524
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 fh=0 readV 2104@105366736
200810 07:25:02 7314 tlhcb008.220:111@htcjob47005_0_slot1_23_pid30299.ralworker XrootdProtocol: 0200 fh=0 readV 14813@105372804

```

xrd-ceph:

```
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0300 open r lhcb:prod/lhcb/LHCb/Collision15/TURBO.MDST/00051290/0002/00051290_00025876_1.turbo.mdst?pss.tid=tlhcb008.220:102@htcjob47005_0_slot1_23_pid30299.ralworker
200810 07:25:17 5116 u102.7:4210@localhost XrootdResponse: 0300 sending 4 data bytes
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 req=readv dlen=13392
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 fh=2 readV 674@71780326
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 fh=2 readV 356@71782997
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 fh=2 readV 813@71783601
==== ~800 readVs snipped ====
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 fh=2 readV 29117@105144524
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 fh=2 readV 2104@105366736
200810 07:25:17 5116 u102.7:4210@localhost XrootdProtocol: 0200 fh=2 readV 14813@105372804
200810 07:26:17 3212 u102.7:4236@localhost XrootdResponse: 0000 sending 55 data bytes; status=0
200810 07:26:17 3212 u102.7:4236@localhost XrootdProtocol: 0000 req=auth dlen=151
200810 07:26:17 3212 u102.7:4236@localhost XrootdResponse: 0000 sending OK
```

Which looks to me like the vector reads are being passed through, as you suspected. I didn't realise this could happen with XCache, I was naively assuming anything would be passed through in blocksize-sized requests.

Looking through the logs at the requests getting through to the xrd-ceph gateways, I see a mix of small irregularly sized vector reads, and properly aligned 64MB reads. I assume from this mix of full block reads and vector reads are the mix of "unwrapped" and "pass through" reads from XCache?

Amusingly(!!?), the ratio of vector reads to reads varies wildly depending on the generation of workernode, and positively correlates with the number of "Operation expired" failures seen on that generation (more vreads getting to xrd-ceph = more job failures of this type). All generations are running the same xrootd configs and LHCb jobs, but have different numbers of job slots and different types of local storage. It might be notable that the newest generation of workernodes has SSDs for local storage, sees no vector reads hitting the xrd-ceph container, and sees no operation expired failures, despite having 3-4x the number of job slots as the other workernodes.

Looking at the Echo monitoring of read operations coming from the LHCb test workernodes over the past day, it looks like the majority of reads Ceph is serving are 64MB as expected:

![lhcb_osd_read_operation_size](https://user-images.githubusercontent.com/9048425/89809177-1e83f180-db33-11ea-9c63-efaae9a4ec52.png)

However, looking at the totals of reads and vector reads from the xrd-ceph container logs for the same period, there are an order of magnitude more vector reads than full block reads. I assume from these two observations that most of the vector reads hitting Echo never finish, as something times out long before the stack of reads can be actioned when they do hit Ceph.

Again, this may be somewhat naive, but from my digging today it looks like we might be able to make things a lot better if we could stop XCache allowing vector reads to be passed through to the origin. I will experiment with increasing the amount of ram it can use (pfc.ram) and reducing the block sizes so larger vector reads can be unwrapped, but I would be interested in understanding if we could explicitly disallow this behaviour. As stated above the xrd-ceph doesn't handle vector reads particularly  elegantly, and Echo block sizes are super inefficient for small reads, so if a vector read is too big to be unwrapped by XCache, it's probably not going to fare much better being passed through to Echo either.

Other things I have looked at/thought about from your comments:

   * Looking at the Ceph -> workernode traffic, I'm not seeing a vast amount more traffic than I would expect. It's definitely asymmetrical, with ~50% more data going into the xrootd container network from Ceph then data coming out of the container network to the job containers, but that sounds pretty good to me, especially given the block sizes. It's certainly not the 39GB of data for a 9MB read levels of bad as far as I can tell.

   * @osschar's comments on block sizes - I do appreciate that large block sizes are never going to be particularly efficient for sparse vector reads, and we have experimented with smaller block sizes, but as the underlying block size in Echo is 64MB, reducing the various xrootd block sizes moves the inefficiency to the Ceph layer, as the 64MB blocks still have to be reconstructed from their erasure coded shards for each operation. Reducing the block sizes significantly impacts the full file copy speed. I would say I'm happy with it somewhere between 16MB-64MB.

   * pss.setopt DebugLevel 3 - I've set this, see the example below. Again, I assume from this that the mix of full block reads and vector reads are the mix of "unwrapped" and "pass through" reads?
```
[2020-08-10 17:27:29.570050 +0000][Error ][XRootD ] [u49@127.0.0.1:1095] Unable to get the response to request kXR_readv (handle: 0x00000000, chunks: 634, total size: 8740387)
[2020-08-10 17:27:29.570107 +0000][Error ][XRootD ] [u49@127.0.0.1:1095] Unable to get the response to request kXR_read (handle: 0x00000000, offset: 1543503872, size: 67108864)
[2020-08-10 17:27:29.570231 +0000][Error ][XRootD ] [u50@127.0.0.1:1095] Unable to get the response to request kXR_readv (handle: 0x03000000, chunks: 899, total size: 2441099)
[2020-08-10 17:27:29.570271 +0000][Error ][XRootD ] [u50@127.0.0.1:1095] Unable to get the response to request kXR_readv (handle: 0x03000000, chunks: 1024, total size: 2757650)
[2020-08-10 17:27:29.570326 +0000][Error ][XRootD ] [u50@127.0.0.1:1095] Unable to get the response to request kXR_read (handle: 0x03000000, offset: 67108864, size: 67108864)
[2020-08-10 17:28:05.373496 +0000][Error ][XRootD ] [u32@127.0.0.1:1095] Unable to get the response to request kXR_readv (handle: 0x02000000, chunks: 685, total size: 9232202)
[2020-08-10 17:28:05.373542 +0000][Error ][XRootD ] [u32@127.0.0.1:1095] Unable to get the response to request kXR_readv (handle: 0x02000000, chunks: 685, total size: 9232202)
```

Thanks again for all your time on this, I really appreciate all the input.

**Comment by abh3** [comment]
Hi Tom,

I guess I am a bit confused by...

"Again, this may be somewhat naive, but from my digging today it looks 
like we might be able to make things a lot better if we could stop XCache 
allowing vector reads to be passed through to the origin. I will 
experiment with increasing the amount of ram it can use (pfc.ram) and 
reducing the block sizes so larger vector reads can be unwrapped, but I 
would be interested in understanding if we could explicitly disallow this 
behaviour."

The reason is that the reads are being forwarded to the origin is because 
XCache doesn't have enough resources (memory in this case) to handle it. 
If the reads were not forwarded then the only two possible actions would 
be a) wait until enough memory becomes available (probably ending in an 
operation expired anyway), or b) simply declaring an error (resulting in a 
failed job anyway).

It would seem to be better to make the Ceph layer coalesce vector reads 
and exctract out as much out of the page to satisfy the incoming vread to 
avoid rereading pages. That said, it doesn't necessarily avoid a failure. 
If we could capture the vector reads (which we can via monitoring) then we 
could make an educated guess. For instance, if 80% of the small reads can 
usually be satisfied from one 64MB page, then the coalescing solution 
would likely work. If it's much less than that, likely not.

Andy

**Comment by osschar** [comment]
Currently, there is no way to disable pass-through (for either single or vector reads). It's definitely possible to do but it's not exactly trivial as it will be the first time we'd be introducing internal xcache delays in read request processing. Assuming this will be an important use case for xcache in the future, I'm willing to bite the bullet ... but you must promise to provide testing :) 

Andy, Brian, what do you think?

You are right that as things stand reducing block-size and increasing pfc.ram are the only two handles available to you.

Two sort of random thoughts:

1. You have disabled prefetching on the cache, right (pfc.prefetch 0) ... this won't matter much when cache is overloaded as prefetching automatically stops when ram usage goes beyond 80%.

2. Could you throw some ssds at the older nodes?

**Comment by osschar** [comment]
Andy, where is the vector read code for Ceph and do we have somebody to bother them about it? This is something that needs to be fixed anyway :)

**Comment by abh3** [comment]
Hi Matevz,

As posted in my previous comment, delaying the read will likely push the 
problem elsewhere and won't get rid of it. I think the better bet is to 
make the Ceph layer more intellegent (assuming the vreads can be satisfied 
with a minimal number of 64MB reads). So, the first thing is to 
statistically map the vreads to see how many pages they are actually 
hitting.

Andy

**Comment by xrootd-dev** [comment]
Hi Matevz,

The code is in the xrootd repo:

https://github.com/xrootd/xrootd-ceph

and is automatically included in git head as a submodule (though normally 
not compiled as Ceph releases are problematic). Unfortuantely, we don't 
have anyone specific. Sebatien used to do this and has since moved on 
though perhaps he would be able to assist. This isn't exactly rocket 
science though it's a bit tricky and definitely needs a working Ceph to 
test with.

Andy

**Comment by osschar** [comment]
Thanks! The problem is that XrdCephOssFile does not implement ReadV at all and so it gets serialized at the parent class level, right?

Also, Read() always calls ceph_posix_pread() which only handles one block at a time and so requires two calls if the request is straddling two ceph blocks.

Would enabling AIO help here? It seems to be implemented there.

**Comment by abh3** [comment]
Correct! That's what has to get fixed. However, there is no point in doing 
this if the majority of a vector read hits individual pages. We need to 
understand the vector read before deciding where to apply limited effort.

Enabling AIO would do nothing as Ceph AIO reverts to synchrnous I/O.

**Comment by bbockelm** [comment]
> As posted in my previous comment, delaying the read will likely push the problem elsewhere and won't get rid of it

This is likely true unless there's temporal locality.  That is, if LHCb happens to revisit the same 64MB block repeatedly, it might be beneficial to slow down and cache it at the WN.  This was the CMS case because CMS scans a single metadata branch scattered throughout the file then reads linearly through the file.

Given how LHCb is nicely using ReadV, I suspect we are not in this exception...

**Comment by abh3** [comment]
Well, that was my exact point. We need to understand whether or not there 
*is* temporal locality (at least within a 64MB page) to figure out where 
this is best solved. Without that knowledge it's basically a whack a mole 
exercise.

**Comment by Tom-Byrne** [comment]
@abh3 In this specific case the XCache passthrough seems to be actively making things worse, hence my suggestion, but I understand in the majority of cases it is sane to pass through the read as is rather than blocking and possibly causing a failure. It makes sense to make the xrd-ceph layer more intelligent, rather than what I suggested. 

@osschar:

1. No, we had not disable prefetch... does it really default to 10? That might make a significant difference with our block sizes and ram allocation. Trying it now.
2. I doubt there is much appetite to retrofit SSDs into old workernodes, but it might be something to bring up. Annoyingly/interestingly, the non-SSD workernodes are do not have universally high rates of this failure and vector reads getting passed through, we have one generation from 2014(!) that is nearly as good as the new SSD nodes, so there is definitely a bit more digging to be done at our end to understand the variance in XCache performance.

**Comment by rajanandakumar** [comment]
Many tanks for the comments. From a non-expert point of view (not having understood everything, though I am trying), I have a couple of questions 

1. Where do we go from here / what next to try?
2. I note that we have so far been using disk proxy in our tests. Using a memory proxy also showed a similar issue. But is it worth re-considering using memory proxies, assuming that the design is very different from disk proxy and likely has different configuration options?

**Comment by abh3** [comment]
Hi Raja,

I think the fist and most important aspect here is to understand the 
locality aspects of the vector reads. One way is to turn on monitoring a 
for a bit and gather statistics on these reads. This will more 
clearly define the solution parameters going forward.

Andy

**Comment by osschar** [comment]
@Tom-Byrne The older nodes, they probably have fewer cores and so pressure on the local cache is smaller. Does this make sense?

How many disks do you have in your WNs? XCache can be configured to use several disks. Usually the disk gets to be the bottleneck so if you can spread the load over several of them this would help a lot already.

**Comment by osschar** [comment]
@abh3 @rajanandakumar It's probably rather hard for people to setup monitoring for analysis of vector reads :)

There are el6 rpms of the gled collector still available (I've managed to build it on fedora 30 a while back but never had the time to pack it back up):
https://twiki.cern.ch/twiki/bin/view/LCG/WLCGDataTransferMonitoring#GLED_Collector

I can help you set it up for collecting detailed read information into ROOT files.

Alternatively, you could send your monitoring information over to a collector here at UCSD, I can spawn off an instance for you.

Or you could get me an example data file / job setup so I can run it here off cvmfs.

**Comment by xrootd-dev** [comment]
I think setting up an instance in UCSD is likely that fastest way of 
addressing this. Could you?

**Comment by osschar** [comment]
Yup, i'll get it up now.

**Comment by osschar** [comment]
OK, please add this to your xrootd config:
```
xrootd.monitor all auth flush io 60s ident 5m mbuff 8k window 10s dest files iov info user xrootd.t2.ucsd.edu:9932
```

**Comment by rajanandakumar** [comment]
@osschar About the test code, could you have a look at 

https://github.com/rajanandakumar/lhcb-ral-test

and let me know if that works for you / is good enough for testing / any issues.

Also, I will have a discussion with @Tom-Byrne tomorrow and will try to get the xrootd.monitor line you mentioned above into the WNs.

**Comment by xrootd-dev** [comment]
Actually, if all of them are suffering the same fate then maybe just one 
will do (or at least the one that most often has the problem). What do you 
think Matevz?

**Comment by osschar** [comment]
Well, we need this info from LHCb jobs ... so ideally this would go on a machine that only runs those. Otherwise it's going to be hard to disentangle. And yes, one machine would be good.

And no, I don't have a lhcb stamped cert :(

**Comment by rajanandakumar** [comment]
You could try with a few root files from any experiment - I will be interested to know the result. But obviously not top priority :)

**Comment by Tom-Byrne** [comment]
@osschar the "good old" workernodes do have less job slots, but only 20% less (32 vs 40) than the generation that sees significantly more failures. I do suspect you're on the right track, these WN disks were never bought with XCaches in mind, so we probably have an range of performances in the various generations. Right away I can see that the "bad" nodes have 2.5 inch hard drives vs 3.5 inch on the others. I'm putting some internal monitoring together to try and understand how hard each of the generations disks are working, hopefully I can find something obvious that correlates with these failures.

I've also added your monitoring to our test WNs, It's easier for me to do it to all 6 WNs reserved for the LHCb test jobs, but if you would prefer a single host I can do that too.

**Comment by osschar** [comment]
@Tom-Byrne good, I can see data being saved, I'll look at it as soon as i can, it's not exactly trivial.

@rajanandakumar it's more complicated than this ... we need actual lhcb jobs and data files to see what they are doing. Different typed of lhcb jobs will also have different access patterns. Actually, what kind of jobs do you expect to run? Reconstruction and user/physics analysis typically have very different read rates and access patterns.

**Comment by rajanandakumar** [comment]
@osschar Indeed LHCb reconstruction jobs have a different access pattern - they copy data directly to the WN and run off the local data. This is possible as we know exactly the size of the input data and have designed it to fit into the minimum storage available per job.

User / physics jobs stream data directly from the storage as the number of input files can be large (user dependent), totalling to 2 - 3 TB of data at times (or even more) - too big to fit into any local storage for the job.

The xrootd monitoring data coming to you are from the test system set up at RAL. These jobs exclusively run a minimal LHCb job which we created on request and reproduces the issue seen by user jobs. Hopefully fixing the problem with these jobs will solve this problem seen by all users (LHCb and possibly others).

**Comment by osschar** [comment]
This is log(10) of number of sub-requests within a vector read - most likely to be between 400 and 1000:
![vrd_num_subreq_cum_log](https://user-images.githubusercontent.com/2625383/90176961-aa2d9600-dd5e-11ea-8ad6-c200165bc68d.png)

This is log(10) of total extent of the vector read, as you can see there are two peaks, 10M and 100MB:
![vrd_tot_extent_cum_B](https://user-images.githubusercontent.com/2625383/90177049-ccbfaf00-dd5e-11ea-9be4-bcd8ce2b3127.png)

This is log(10) of individual sub-requests in a vector read, most likely 1kB, up to 100kB:
![vrd_extent_cum_B](https://user-images.githubusercontent.com/2625383/90177072-d47f5380-dd5e-11ea-9ac2-fe1163e0d604.png)

And log 10 of individual gaps between sub-requests, two peaks, 1kB and between 100k and 200k:
![vrd_inner_offs_cum_B](https://user-images.githubusercontent.com/2625383/90177080-d6491700-dd5e-11ea-9ae0-c70ed31c7439.png)

To summarize, if this sample is representative (52 k file accesses, 2.4 M vector read requests), this should actually work rather well with xcache and block size 64 M -- typical vector read will require about 2 blocks to serve it.

Now, if these vector reads indeed get to the ceph server, they will wreck havoc as they will be reading the same block about 500 times to get about 1 k to 200 k of data out. Fixing vector reads on the xrootd-ceph will indeed help.

@rajanandakumar  Are there two different types of jobs being run here? Or maybe some of them fail?

My analysis program reports that there are some request offsets that go beyond the end-of-file.

Are these jobs exceeding now? I assume, if they fail, we won't get the full picture ... so we really want them to make it to the end.

**Comment by rajanandakumar** [comment]
@osschar Thanks for the nice plots and more importantly the summary. I am still trying to understand them and the implications. To answer your questions, the following points may help

1. All test jobs (feeding into this plot) are identical except for the input files - 12 files are randomly picked from a list of about 2000.
2. Final status of the jobs : Some jobs succeed. Some jobs are killed by DIRAC as having been found to be stuck (CPU efficiency < 5% - "Watchdog identified this job as stalled"). The remaining jobs have failed with the error we are concerned with here - this is the "application finished with errors" in the following monitoring page 
http://lhcb-project-dirac.web.cern.ch/lhcb-project-dirac/RALEchoTestMonitoring.html
3. There is no way I can guarantee a job to be successful streaming data. This is the real problem that a given job can fail once, and succeed another time on the same machine, with the same input files and had led to so much puzzlement and time spent on this issue.

I am guessing that the monitoring information you get is not by job. As a result, there is no easy way for me to tell you if a file got fully streamed or not. All I can tell you is about 3% of jobs succeeded recently (last 24 hours) which implies, one of its input 12 files failed to stream fully. From experience, this can happen at any point in the streaming of the file.

**Comment by osschar** [comment]
I get information per client session and per file read ... so I can select individual jobs based on "global" properties of the file access. 

Looking at  plots of duration the file was open and the fraction of file was read, I see that if I select files that read close to 100% of the file and are open for 1000 - 3000 s I get about 6% of the total number of jobs -- these might be the successful ones. This is the bump in the top-right of the lego plot below.

Now, this isn't really the access pattern CMS sees for analysis jobs on AOD / MiniAOD data, it's more likely to read some fraction of data (as not all branches are accessed), can be anything from 10 to 60%. On NANO/MICRO AOD one would expect the file to be read in full. Do you know what data-tier we have here and if it is expected that the job would read every branch in the file?

![open_duration](https://user-images.githubusercontent.com/2625383/90193636-34cfbe80-dd7a-11ea-8b6a-2421834cc117.png)
![frac_read](https://user-images.githubusercontent.com/2625383/90193644-38fbdc00-dd7a-11ea-9ed4-1cd6f8dde585.png)
![title](https://user-images.githubusercontent.com/2625383/90193650-3b5e3600-dd7a-11ea-9bd6-7005642c6648.png)

**Comment by rajanandakumar** [comment]
I do not know the details of the interaction between root and LHCb applications, though I suspect that as you suggest, only part of the data is read for most analysis jobs.

In the case of these test jobs, however the whole of the file is scanned and the list of paths where some data is stored is dumped in a log file (happily discarded for this test). This is the simplest / most trivial working example we have to reproduce the error seen in user jobs at RAL. We could reproduce the issue with a more complicated job also I suppose.

Did I understand from your previous comment (https://github.com/xrootd/xrootd/issues/1259#issuecomment-673668930) that development on the CEPH side is needed?

**Comment by osschar** [comment]
If you are not running real jobs, we won't know the real access patterns. The way things are now, it's easy to break the setup ... but we need to know how it gets broken with real jobs so we can fix it the right way.

If these were the real jobs, implementing vector reads properly in xrootd-ceph interface would have fixed the problem.

**Comment by rajanandakumar** [comment]
@osschar my apologies if I do not understand what you mean by "real jobs". 

A job of this type is run fairly regularly. What conclusion will be different if the test jobs are different?

**Comment by osschar** [comment]
Oh, I thought you said these jobs do full file scan and not actual physics analysis (which could access data in a different manner than "get full event data for every event" kind of test). I'm not saying the actual physics analysis does not do the same thing ... in some cases it does, that's why I've been asking about the data-tier etc :)

I will re-run the monitoring data analysis on Monday, selecting only access that read all the file to see if things change drastically. I don't think it really will as vector reads follow the same pattern for both successful and failed jobs ... they just end sooner for failed jobs.

While fixing the xroot-ceph to be smarter about vector reads will help a lot (and needs to be done anyway because as things are now it just calls for trouble whenever vector reads hit ceph) as it will allow it to read a block once instead of 500-times for each vector read request, it will still have to read the same block about 64M/200k ~ 300 times to satisfy successive vector read requests that hit the same block.

You still need to figure out why xcache is failing so badly on some machines and figure out what you are prepared to do to alleviate the situation ... it could be:
- throwing more disk (spindles or ssd) on "bad" worker nodes; or
- setting up a high-performance / volume xcache instance and directing the "bad" worker nodes to use it.

I don't know enough about ceph to understand if there is a chance of buffering / caching in the ceph access points ... but this would likely saturate at some point as well and having outside / xcache-like buffers is the only scalable way.

**Comment by osschar** [comment]
Here are the plots for jobs that read more than 98% of file with additional data that came in over the weekend (total of 179k jobs, 10.6k passes the cut -- about 6%):
![full_file_read](https://user-images.githubusercontent.com/2625383/90427212-179b3880-e077-11ea-8c20-4c27b1e737a5.png)

Now, see how drastically different they are:
1. number of subreqs in a vector read is below 100, it was up to 1000 before.
2. total extent of vector read (first to last byte) is smaller
3. sum of subreq extents is far on the large size
4. offsets within the vector read are much smaller

This clearly makes it easier for cache to keep up (fewer blocks to request at the same time) and also, when the vector read hits ceph, it has 10-times less vector reads to process (and they are larger individually, too).

Now, assuming the jobs are all the same ... it looks like you have files with different basket sizes and event cluster sizes in the mix. I tried to see a pattern in LFNs but there doesn't seem to be one. File size also doesn't seem to matter, I see the sizes are typically between 2 and 8 GB, with some files below 100 MB.

**Comment by rajanandakumar** [comment]
Hi @osschar ,

Thanks a lot for the two detailed analyses. A few questions :

1. In the case of whole reads, does CEPH still have to read a block >>1 times to get the needed data out?
2. In any case, If I  understand correct, fixing the vector reads on the xrootd-ceph can only help. I am guessing that this will be done by someone with xrootd knowledge, and I would be happy to do my best to test it at the RAL end if possible / needed. A timescale for this would be useful.
3. We are also investigating one set of WNs here at RAL which seem to have multiple issues (ncluding these failures). I will let you know if we find anything about it.

Thanks and Cheers,
Raja.

**Comment by abh3** [comment]
Hi Raja,

Indeed, Ceph reads the block multiple times, one for each call to read 
that block. As for experience needed, alsmost any good C++ developer could 
do this. The code is enacsulated in a plugin with little xrootd 
entanglement. Likely, they would need to know more about Ceph than xrootd.

Andy

**Comment by rajanandakumar** [comment]
Dear all,

Apologies for not saying more here. At RAL we will be working on fixing the vector read issue. We have also done some fine tuning of the parameters with our better understanding and it has apparently already helped Atlas jobs. 

Back to LHCb, when we used Dump for the xrootd log level we got a lot of information. However the huge amount of data dumped also caused failures. 

So we tried with log level Warning. But most of the time we now do not get any xrootd debug information even when the main process exits in the middle of reading a file (except for about 5% of failures with "Operation expired"). What do we do to get logging in this case?

Thanks and kind regards 
Raja

**Comment by osschar** [comment]
Hi,

You mean pfc.trace? You can also send it to info or debug ... dump is totally excessive for production.

Cheers,
Matevz

**Comment by rajanandakumar** [comment]
Hi,

Just to be really clear - I mean that in the application, I set the following:

export XRD_LOGLEVEL=Dump

As you said, it was excessive. i will try info next.

Cheers,
Raja.

**Comment by osschar** [comment]
Oh, that's different than pfc.trace ... what messages are you actually after? Andy and I can then tell you what to set.

Cheers,
Matevz

**Comment by rajanandakumar** [comment]
Hi,

We are looking for the cause of job failures. In this case the job basically stops receiving data from the "storage". 

So we are looking for the options to set for the above. 

Cheers 
Raja

**Comment by osschar** [comment]
Oh, I thought you had a specific set of messages you've already been looking at / using.

I'd expect it to have something to do with timeout error received from the job ... I'm not sure if this is how the protocol works.

Andy, is there such a thing as error disconnect from the client? Under what trace does it get printed out?

Cheers,
Matevz

**Comment by xrootd-dev** [comment]
Yes, it's usually operation expired error and there is no fallback so it 
returns the error to the application. Tracing at the "Error" or "Debug" 
level will display the message.

**Comment by abh3** [comment]
I think we understand that this is a problem involving load in the presence of a vector read. RAAL is in the process of implementing vector reads in he Ceph plugin. I am going to keep this open in until this process is complete and tested.

**Comment by abh3** [comment]
Discussion closed.
