### ISSUE TITLE
xrdcp fails against dCache TPC when -C specified

### ISSUE THREAD

**Issue by alrossi** [xrootd/xrootd#1359]

**Comment by alrossi** [comment]
Hello,

It seems we have a problem which has gone undiscovered with dCache since May.   

```
[arossi@fndcatemp1 xrootd]$  xrdcp --tpc delegate only  root://fndcatemp2.fnal.gov:1095//pnfs/fs/usr/test/arossi/volatile/cksumtest root://fndcatemp2.fnal.gov:1097//pnfs/fs/usr/test/arossi/tape/0/cksumtest-`date | tr ' ' '.'`
[1B/1B][100%][==================================================][1B/s]  
```
but

```
[arossi@fndcatemp1 xrootd]$  xrdcp --tpc delegate only -C adler32  root://fndcatemp2.fnal.gov:1095//pnfs/fs/usr/test/arossi/volatile/cksumtest root://fndcatemp2.fnal.gov:1097//pnfs/fs/usr/test/arossi/tape/0/cksumtest-`date | tr ' ' '.'`
[1B/1B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3013] Request 3001 not supported Got an error while querying the checksum! (destination)
```

The following commit seems to be involved:

```
3a1be817e5e90bb6ea4667077d02c30c5d774018 is the first bad commit
commit 3a1be817e5e90bb6ea4667077d02c30c5d774018
Author: Michal Simon <michal.simon@cern.ch>
Date:   Tue May 12 18:50:14 2020 +0200
    [XrdCl] Preserve xrdcl.* cgi elements on redirect as they are important for the internal workflow.
```

though it is difficult to say with certainty, as the preceding commit

```
commit 93c885978c564c380d3b82c4ac7739e16e72492c (HEAD)
Author: Michal Simon <michal.simon@cern.ch>
Date:   Tue May 12 14:57:27 2020 +0200

    [XrdCl] Make sure xrdcl specific cgi is not propagated to server.
```

hangs against the pool.   From the debug output on the latter, we see that the transfer succeeds but that there is no response on close

```
[1B/1B][100%][==================================================][1B/s]  [2020-12-09 12:04:27.545898 -0600][Debug  ][File              ] [0x1e0e8b0@root://fndcatemp2.fnal.gov:1097//pnfs/fs/usr/test/arossi/tape/0/cksumtest-Wed.Dec..9.12:04:26.CST.2020?oss.asize=1&tpc.dlg=fndcatemp2.fnal.gov:1095&tpc.dlgon=1&tpc.key=16d7f326505d10c25fd111aa&tpc.lfn=/pnfs/fs/usr/test/arossi/volatile/cksumtest&tpc.scgi=tpc.stage=placement&tpc.spr=root&tpc.src=fndcatemp2.fnal.gov:1095&tpc.stage=copy&tpc.str=1&tpc.tpr=root&xrdcl.intent=tpc&xrdcl.requuid=e344949b-64a2-4eff-b6b4-b494a705fbff] Sending a close command for handle 0x0 to dcatest03.fnal.gov:33123
[2020-12-09 12:04:27.545944 -0600][Dump   ][XRootD            ] [dcatest03.fnal.gov:33123] Sending message kXR_close (handle: 0x00000000)
[2020-12-09 12:04:27.545978 -0600][Debug  ][ExDbgMsg          ] [dcatest03.fnal.gov:33123] MsgHandler created: 0x1e15000 (message: kXR_close (handle: 0x00000000) ).
[2020-12-09 12:04:27.546009 -0600][Dump   ][PostMaster        ] [dcatest03.fnal.gov:33123] Sending message kXR_close (handle: 0x00000000) (0x1e0ecc0) through substream 0 expecting answer at 0
[2020-12-09 12:04:27.546069 -0600][Dump   ][AsyncSock         ] [dcatest03.fnal.gov:33123.0] Wrote a message: kXR_close (handle: 0x00000000) (0x1e0ecc0), 24 bytes
[2020-12-09 12:04:27.546122 -0600][Dump   ][AsyncSock         ] [dcatest03.fnal.gov:33123.0] Successfully sent message: kXR_close (handle: 0x00000000) (0x1e0ecc0).
[2020-12-09 12:04:27.546143 -0600][Dump   ][XRootD            ] [dcatest03.fnal.gov:33123] Message kXR_close (handle: 0x00000000) has been successfully sent.
[2020-12-09 12:04:27.546159 -0600][Debug  ][ExDbgMsg          ] [dcatest03.fnal.gov:33123] Moving MsgHandler: 0x1e15000 (message: kXR_close (handle: 0x00000000) ) from out-queu to in-queue.
[2020-12-09 12:04:27.546182 -0600][Dump   ][PostMaster        ] [dcatest03.fnal.gov:33123.0] All messages consumed, disable uplink
```

Be that as it may, our working hypothesis concerning the checksum issue is that, prior to this commit (at least in the 4-series client), the checksum request was issued on the same session, whereas in the new client this is a separate session.  

Issuing a separate request to the pool endpoint, however, is currently not going to work, because it is lacking the UUID for the transfer generated on open at the door, and also because the new connection does not indicate where to redirect (which door), information also obtained from the original open request, which is not present.

We would like to understand whether this is indeed the case, and whether this behavior could be modified on your end so that xrdcp and dCache are once again interoperable using TPC.

Thanks!

Al

**Comment by paulmillar** [comment]
If it helps, this is a description of the problem from a dCache pool's perspective.

```
level=INFO ts=2020-12-08T18:57:10.177+0100 event=org.dcache.xrootd.connection.start session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 socket.remote=[2001:1458:301:cd::100:c4]:37906 socket.local=[2001:638:700:10bf::1:43]:33185
level=INFO ts=2020-12-08T18:57:10.177+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=protocol response=ok
level=INFO ts=2020-12-08T18:57:10.229+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=login username=fts3 capver=5 pid=31464 token=?xrd.cc=ch&xrd.tz=1&xrd.appname=fts_url_copy&xrd.info=&xrd.hostname=fts-pilot-002.cern.ch&xrd.rn=v5.0.3 response=ok sessionId=4C832115EE857E067C233352972F0B6E
level=INFO ts=2020-12-08T18:57:10.260+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=open path=//escape/wp2_rucio_testbed/desy_dcache/fts-testing/dest/fts.testfile.ca2efc4c-397e-11eb-8a4c-fa163e0a532b opaque=org.dcache.uuid=04121253-9f70-4458-9544-f63e52f62ee2&org.dcache.xrootd.client=fts3.31464@fts-pilot-002.cern.ch&oss.asize=1048576&tpc.dlg=eoseulake.cern.ch:1094&tpc.dlgon=1&tpc.key=2d26252d64117ae85fcfbe75&tpc.lfn=//eos/eulake/tests/rucio_test/eulake_1/fts-testing/src/fts.testfile.52ae7806-0df4-11eb-9b92-fa163ef9255e_1mb&tpc.scgi=cap.msg=WCsnX2zfIcjzTKauAk/8lol79gDZzvutgxkdGiMAec2m+07UzzC73sfLw6t8iV5oj29Pr3Wx5pZDbkdhfskhk6PimoTwDSNK5yI0lm1vYBjxlaIx5nBUOVEjgOz6ikYVYsYLPsjO41OgpHuG/rbSL+QEbiraX1mN6Oze+I7ynUeDYPhaWYGVmod9nKAHTQSHF5rZwnyZaeJ7Xm739lBAjfQz26vRU8necJ+iQxwxOFg6oB6leOpa8XZMtASLYy8CT3bn7eeNJq8VbUT68X49vp9ZPdPgyPWM2t/g55PH7ia07bMdcu3JE9iv016v+nl7sDyAZEnm+kUilYngax+Nehqpds+u39WKgB/GkqXSt/+IOlHATTqjpbdDzcv12zMemF4G+117KBrBwqycibbRW4rmhSD8WJT0VddXOVbqoFEg0+/8GunroXuXxHgJMz5IhR8nqqwdlbeQ1SnNf80GRGXmn9p9bNTnAdnVjIdGPYJeQeesAbUY1uhsaFi0W7GWqC967QHL1QhQVUvSowElSxB8FHt+Lq/Iyh0cYzr1Z+Uv03Z3Aebn0srCxec+Xs+o5BLacVvkhhE6aZa/ZW3Rk5Td6mM7RtI/y26uFRml0/E=      cap.sym=IXwTCS5luchuJsEVdO71eGA8pFc=    mgm.id=0357e543 mgm.logid=cae3eb16-397e-11eb-b697-0cc47a697326      mgm.mtime=1602662857    mgm.replicahead=0       mgm.replicaindex=0      tpc.stage=placement     xrd.gsiusrpxy=/tmp/x509up_h13309331254104230041XdcXchXdcXcernXouXorganicXunitsXouXusersXcnXewp2c01XcnX817926XcnXrobotXXescapeXwp2XcernX01&tpc.spr=root&tpc.src=p05151113691315.cern.ch:1095&tpc.stage=copy&tpc.str=1&tpc.tpr=root&xrd.gsiusrpxy=/tmp/x509up_h13309331254104230041XdcXchXdcXcernXouXorganicXunitsXouXusersXcnXewp2c01XcnX817926XcnXrobotXXescapeXwp2XcernX01 mode=0 options=0x468 response=ok handle=0 flags=0 modtime=1970-01-01T00:00:00Z size=0
level=INFO ts=2020-12-08T18:57:10.314+0100 event=org.dcache.xrootd.connection.start session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:326cc5ce socket.remote=[2001:1458:301:cd::100:c4]:37912 socket.local=[2001:638:700:10bf::1:43]:33185
level=INFO ts=2020-12-08T18:57:10.314+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:326cc5ce request=protocol response=ok
level=INFO ts=2020-12-08T18:57:10.366+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:326cc5ce request=login username=fts3 capver=5 pid=31464 token=?xrd.cc=ch&xrd.tz=1&xrd.appname=fts_url_copy&xrd.info=&xrd.hostname=fts-pilot-002.cern.ch&xrd.rn=v5.0.3 response=ok sessionId=6761F42E87D7719DAEEA92CA5BDDC05A
level=INFO ts=2020-12-08T18:57:10.393+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:326cc5ce request=query response=ok
level=INFO ts=2020-12-08T18:57:10.447+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=sync handle=0 response=ok
level=INFO ts=2020-12-08T18:57:11.181+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=sync handle=0 response=ok
level=INFO ts=2020-12-08T18:57:11.483+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=stat handle=0 vfs=false response=ok flags=0 modtime=2020-12-08T17:57:10Z size=1048576
level=INFO ts=2020-12-08T18:57:11.542+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848 request=close handle=0 response=ok
level=ERROR ts=2020-12-08T18:57:11.678+0100 event=org.dcache.xrootd.request session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:326cc5ce request=query response=error error.code=Unsupported error.msg="Request 3001 not supported"
level=INFO ts=2020-12-08T18:57:11.773+0100 event=org.dcache.xrootd.connection.end session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:326cc5ce
level=INFO ts=2020-12-08T18:57:11.773+0100 event=org.dcache.xrootd.connection.end session=pool:dcache-doma04-01@dcache-doma04-01Domain:xrootd:810e3848
```

What you're seeing is the pool's access log file.  Each line shows either an xroot requests (with the corresponding response from the pool), a TCP connection event, or a TCP disconnection event.

Here's a high level summary of what happened:
1. The client (xrdcp) requests a xroot-TPC from the door and is redirected to the pool (this isn't shown),
2. The client (xrdcp) connects to the pool (TCP-1).  This is first line in access logfile.
3. On TCP-1, the client does `kXR_protocol`, `kXR_login` and `kXR_open` (establishing parameters for the xroot-TPC)
4. The client makes an additional TCP connection (TCP-2)
5. On TCP-2 the client does `kXR_protocol`, `kXR_login`, and `kXR_query` requests.
6. On TCP-1, the client does `kXR_sync` (starting the transfer) and another `kXR_sync` to be notified when the transfer is complete.
7. Transfer completes successfully.
8. On TCP-1, the client does `kXR_stat`
9. On TCP-1 the client does `kXR_close`
10. On TCP-2, the client does `kXR_query` to request the file's checksum --- This fails. 
11. Client closes both TCP-1 and TCP-2.

In xrootd v4.12 and earlier, the `kXR_query` that requests the file's checksum was made on the same TCP stream as the `kXR_open` request.

The checksum query fails because it was made over a different TCP connection from the one in which `kXR_open` was made.  This is (in part) to do with how permissions are handled in dCache pools.

We can try to fix this in dCache but, to be honest, I don't understand the motivation for creating a second TCP connection ("TCP-2", above).  It wasn't needed in earlier versions of xrootd (e.g. v4.12) -- it looks like a bug.

**Comment by alrossi** [comment]
Thanks, Paul.  It seems to me that there was a change at this time involving multiple streams, but I will let Michal et al respond as to what the change was made for.

**Comment by simonmichal** [comment]
@alrossi & @paulmillar : thanks for reporting this incompatibility with dCache and for the detailed description of the problem.

It is an intentional behaviour, the rational behind it is that the server might be configured to enforce encryption only for TPC orchestration: `xrootd.tls tpc`. Therefore whenever the client wants to execute a TPC, it has to open a new connection to the server indicating in the protocol request that this connection is meant for TPC orchestrating (`kXR_ExpTPC`). The server in the protocol response, in turn, will let the client know if the connection should be upgraded to TLS.

At the moment I don't see other way of implementing it, other than using a separate connection for TPC orchestration.
Would it be a big hassle to support this on dCache side?

**Comment by alrossi** [comment]
Thanks, Michal.  I thought I remembered some discussion of this.

I'm not sure I understand why the connection (TCP-1) which does the open (which is the one which passes path and opaque data to our TPC client) doesn't also do the checksum query.

And as far as we are concerned, we do not support (never have) multiple sessions using bind.   

So I presume that the only solution to this problem is for us somehow to support arbitrary queries for checksums on pools.  Currently I do not know what the security implications of this are.

**Comment by simonmichal** [comment]
Well, I suppose we could also bend the rule and say that the checksum query is part of the TPC mechanism and use the potentially encrypted connection. It doesn't sound like something awful to me ;-) I'll try to prepare a patch tomorrow for you to test, would this be OK?

**Comment by alrossi** [comment]
If that solution does not present other complications on your end and is easy to implement, that I would be interested in testing it, yes.

If this doesn't work out, we will try to come up with a plan B (without going the full extent of implementing kXR_bind, which could requires a bit more effort).

Thank you!

**Comment by simonmichal** [comment]
Just a remark: the second physical connection you guys see is not a data stream created with `kXR_bind` but just an independent connection.

**Comment by alrossi** [comment]
Ah, OK.  So bind wouldn't work anyway.

**Comment by simonmichal** [comment]
@alrossi : I just pushed 9fb8851be9865ddd372029993dc180e62a44c51d, could you give it a try?

**Comment by paulmillar** [comment]
@simonmichal I just tried.  It looks good!

**Comment by paulmillar** [comment]
@simonmichal , I can also give you access to prometheus.desy.de, so you can test these things yourself.

**Comment by simonmichal** [comment]
@paulmillar : thanks for testing! having access to a dCache instance certainly would be handy :-)

**Comment by paulmillar** [comment]
@simonmichal , you asked:
> Would it be a big hassle to support this on dCache side?

I've been thinking about this and the short answer is "yes, it would be a big hassle", but perhaps an explanation might lead to future improvements.

The original idea for xroot support in dCache was that the door handles all namespace (non-data) operations, while the pool handles requests directly involving the file's data.  So, when a client does `kXR_open` on a file (in the door), dCache would ensure the file is available from a pool (for reading) or that there is a pool ready to accept the data (for writing).  In either case, the pool promises to accept the client and the door returns that promise in the form of a single-use bearer token, which the client then presents to the pool when making the `kXR_open` request (it's part of the opaque).  If the client makes any other requests to the pool (including a subsequent `kXR_open` request) then it is redirected back to the door.

This bearer token is important because, by presenting it, the pool knows the client has authenticated (to the door) and is authorised to read the file.  Without this token, the pool (currently) doesn't know if the client is allowed to read the file or upload data.  A side-effect is that the client doesn't need to undertake strong authentication when connecting to the pool (for example, no GSI authn).

Later, we allowed some non-data related client requests on the pool (`kXR_stat`, `kXR_query/QCksum`).  These are allowed _after_ the client as issued `kXR_open` with the bearer token in the opaque, since this authenticates and authorises the client.  However, these requests are only allowed against the opened file, if the client were to issue `kXR_query/QCksum` against another file then the pool will redirect the client back to the door.

The problem comes when a client connects and issues a request (e.g., `kXR_query) without first making a `kXR_open` request with an opaque token.  In this case (I believe) we currently don't have any good way to connect this new client connection with any previous client activity.  This is a problem, as the client didn't authenticate strongly (so the pool doesn't know the client's identity) and the pool doesn't know from which door the client came (so the pool cannot redirect the client back to the door).

So, the pool can try to figure out to which door it could redirect the client.  This is tricky, since different doors could have different behaviours (allowed authentication, root directory, namespace mapping, etc).  I'm not sure if this could be solved for the most general case.

As a possible long-term consideration: would it make sense to allow a redirection response to include some kind of token that the client should present on login?

**Comment by paulmillar** [comment]
> @paulmillar : thanks for testing! having access to a dCache instance certainly would be handy :-)

Just drop me an email and I'll set up up.

**Comment by alrossi** [comment]
> As a possible long-term consideration: would it make sense to allow a redirection response to include some kind of token that the client should present on login?

I was also thinking about the possibility of  sharing opaque data between these TCP connections.   The client just forwards the original dark data onto the second connection.  That would probably also solve the issue, but I imagine there would be a host of reasons why this idea might not be desirable inside the xrootd client.   I had not thought of the possibility Paul mentions, though.  I believe the protocol does indeed support a slog for a token, so this might indeed be a feasible route.

Thanks Paul for expanding my original gnomic statement into an understandable narrative (smile).

**Comment by simonmichal** [comment]
`As a possible long-term consideration: would it make sense to allow a redirection response to include some kind of token that the client should present on login?`

Well, I don't think this would help us much, as xrootd client is reusing once opened connections. Even in case of `xrdcp` we are issuing a `kXR_stat` request ahead of using the `CopyProcess` (the component that encapsulates the transfer logic), which opens a physical connection that is NOT TPC specific (and there's even more chance of a scenario like that in case of experiments' frameworks). Before my patch (9fb8851), the query checksum request was going through a connection that was opened before the TPC was carried out.

**Comment by paulmillar** [comment]
> Well, I don't think this would help us much, as xrootd client is reusing once opened connections. 

The only problem we have is that, if a client connects to a pool node and (after login) immediate makes an unexpected request (`kXR_query`, `kXR_rm`, ...) the pool doesn't know to which door it should redirect the client.  If the pool knows from which door the client was redirected, then it can simply respond with a `kXR_redirect` back to the door.

So, imagine that the door, when redirecting the client to the pool, also includes the door's hostname and port number as a token.  If the client presents this information when authenticating (`kXR_login`) then the pool will always know to which door is should redirect the client, if the client makes a request not supported on the pool.

Sorry, I was being lazy and didn't look at the spec.  I see there *is* a token that the client relays to the pool on redirect.  I think it should be easy to update dCache so the door includes its endpoint as this login token.  The pool would uses this information to know where to redirect the client, if the client makes a request that is not supported by the pool.

**Comment by abh3** [comment]
Hi Paul,

On Thu, 10 Dec 2020, Paul Millar wrote:

> As a possible long-term consideration: would it make sense to allow a 
> redirection response to include some kind of token that the client 
> should present on login?
The xroot protocol allows exactly this kind of behavior on a redirect. The 
only issue is what if the client is already logged into that node?

https://xrootd.slac.stanford.edu/doc/dev50/XRdv400.htm#_Toc54039186

Andy

**Comment by paulmillar** [comment]
Hi Andy,

Thanks for confirming that the client will present the token during the login phase, when redirected from the door to the pool node.

I'm working on the assumption that the door's public endpoint remains static over the lifetime of a specific client's interaction.  The endpoint can change (as interfaces are brought up or are taken down) but these are rare events.  Even then, if the client is transferring data then there is already a back-channel through which the pool can learn of changes to the public endpoint.

So, I _think_ this is OK, but testing and production use will ultimately verify if this is true.

Cheers,
Paul.

**Comment by alrossi** [comment]
Paul's suggestion of course depends on the redirect of the client.  If the client tries to open a second TCP directly to the node to which the first client has been redirected, all bets are off of course.   It is not clear from the log whether

```
On TCP-2 the client does kXR_protocol, kXR_login, and kXR_query requests.
```

has also logged into the door first.

Al

**Comment by xrootd-dev** [comment]
Hi Paul,

I believe I said "can" not "will". There is no code at the moment to 
capture the token and resubmit it. Generally, that shouldn't be necessary 
as th tokens present in the CGI part should be preserved. What we are 
taking about here is if there is a token (or needs to be a token) on a 
redirect that needs to be presented at login can be correctly forwarded. I 
am still trying to fully understand the problem here as redirects on 
requests should continue to forward the tokens that are part the 
redirected request (if there were any).

Andy

**Comment by alrossi** [comment]
Michal, when you said above

```
 Before my patch (9fb8851), the query checksum request was going through a connection that was opened before the TPC was carried out.
```
was that connection opened on the door?  I suppose it must have been, if the open which does TPC had not gotten the redirection to pool yet.  

Just as a matter of clarification as to what is going on.

Thanks.

**Comment by alrossi** [comment]
I have not examined the `xrdcp` code, but I have to agree with Andy that what was going wrong with the original implementation is mysterious.   The info returned to the client on redirect should include the dCache UUID.   If the TPC connections 1 & 2 are opened against the redirected endpoint after that, why don't they both make use of the same opaque data?   If they did, then it wouldn't matter much which one did the checksum request.

**Comment by simonmichal** [comment]
> Issuing a separate request to the pool endpoint, however, is currently not going to work, because it is lacking the UUID for the transfer generated on open at the door, and also because the new connection does not indicate where to redirect (which door), information also obtained from the original open request, which is not present.

@alrossi : from the comment above I gather that the UUID is generated only on open, is this correct? If yes, there's no mystery, the open is issued only on one of the connections so the other cannot have the token.

This is what is happening in `xrdcp` (but also what could happen with any experiment framework using `CopyProcess`):

- before using the `CopyProcess` the client is doing a stat, this creates a physical **connection 1** to the server

- then the client is using `CopyProcess` to carry out the transfer, since this is a TPC and the `CopyProcess` doesn't know if the server will require it to be encrypted, it has to open a second physical connection, call it **connection 2**, that is dedicated to TPC, using this connection the file is being opened, transferred and closed

- afterwards, the client is issuing a query checksum request, which technically is not part of TPC so before 9fb8851be9865ddd372029993dc180e62a44c51d it was using **connection 1** that, I suppose, does not have the UUID token because there was no `open` done on this connection


Now, the big question for me is: why does the query checksum request requires the UUID? It is a stateless request, it shouldn't require the file to be opened.

**Comment by alrossi** [comment]
Let me try to recap what happens with dCache.  Here is a rough schematization of what happens when communicating with dCache:

![Screen Shot 2020-12-14 at 07 46 01](https://user-images.githubusercontent.com/3985564/102088745-f0fccc80-3de0-11eb-943b-6f213042c48c.png)

What is unclear to me is:  which open are we talking about?   That is, are these TCP connections we are discussing to the door or to the pool?  (i.e., what do you mean by "the server")? If they are both the door, then I do not understand why the checksum request ends up going to the pool (it should go to the door, and if that connection has been authorized and the user has permissions on the file, then it should succeed –– that is, checksum requests for arbitrary paths are supported on the door).   If they are both to the pool, then the UUID should already be visible to both from the redirect response that a previous open received from the door.   

Also, let me correct something I said in my last reply.   Even with a UUID shared between the two TCP connections, it is not currently guaranteed that the corresponding mover on the pool will be found, because if the connection which does the open and transfer calls close first, the record of that mover will be deleted.   Unlike the door, pools do not have general access to the underlying namespace, but can only serve requests on currently active movers/files.   So if the mover is already closed and deleted, even with the UUID things would currently fail because the connection that did not call open did not convey the endpoint from which it was redirected to the pool.  Paul has provided a series of patches which "fixes" this situation, provided the login token is used as he discussed.

**Comment by simonmichal** [comment]
@alrossi : OK, I see what you are saying, yes the checksum query was going directly to the pool, to the same data server that was the target of the TPC (but on a different connection). It is implemented this way so it can work with vanilla xrootd redirectors. For example, EOS is handling this type of requests by redirecting to the head node (`MGM`).
(maybe what I wrote in my previous comment was misleading, please disregard it)

A side question, how is dCache handling `kXR_stat` requests send to the door, are they redirected to the pool, or resolved directly at the door?

**Comment by alrossi** [comment]
The situation with stat is similar.   Doors resolve them directly, provided permissions are correct.   Pools will redirect back to the door stat requests that express a path; however, if a file handle is provided, the pool can attempt to service the stat directly.

**Comment by paulmillar** [comment]
Hi @simonmichal,

Would there be any problem with back-porting [commit 9fb8851](https://github.com/xrootd/xrootd/commit/9fb8851be9865ddd372029993dc180e62a44c51d) to the `stable-5.0.x` branch, so it could be included in the next v5.0 release?

To be honest, the patch sounds (to me) like a bit of a hack: xrdcp's current behaviour seems to be perfectly spec compliant.  Therefore, I would like to provide a better solution within dCache: one that doesn't require xrdcp to "tip-toe" around like this.  Although the patch solves this specific issue, the problem could come back in the future under a different guise.

From reading the xroot spec, I believe that if dCache returned a token (as part of the `kXR_redirect` response) then the pool would be able to support all requests without returning this error.  The pool would always know from which door the client came (via the token) so, for any query the pool does not support, it can always redirect the client back to the door.

However, during my first steps in this direction I'm seeing inconsistent (and seemingly incorrect) behaviour.  Sometimes xrdcp presents the door-supplied token during the subsequent `kXR_login` request; sometimes it uses some kind of default token.  I haven't figured out what is causing this, so I cannot say if the problem lies in dCache, our xroot Java library (xrootd4j), or XrootD.  Whatever the cause, It will require more time (and more work on my part) before this solution is ready.

Since your patch is available right now, (if there's no objection) my suggestion is that your patch be back-port so it will be include with v5.0.4.  For me, doing this would close this issue, and removes the immediate pressure to find a solution.

Meanwhile, I can try to understand what's going wrong (for me) with redirects and login tokens.  I would then open a fresh issue if that work leads to any concrete questions about the xroot spec or XrootD.

Cheers,
Paul.

**Comment by simonmichal** [comment]
@paulmillar : absolutely, I'll do the back port right away!

**Comment by simonmichal** [comment]
Done: 5c260a9cf142764d653abfe812cb1a6b2b8552a3

**Comment by paulmillar** [comment]
@simonmichal Thanks!

**Comment by paulmillar** [comment]
Is there an estimate when v5.0.4 will be releases?  It's perhaps not so urgent, but it would be helpful if this new version could be deployed on the FTS-pilot instance, as this would resolve the problem we're seeing within the ESCAPE project.

**Comment by simonmichal** [comment]
@paulmillar : we are currently in the release process for `5.1.0`, I AFAIK @mpatrascoiu is going to install 5.1.0-rc3 in the FTS pilot.

**Comment by mpatrascoiu** [comment]
Hello all,

FTS3-Pilot has been updated to the latest `5.1.0-rc3` version.
This update has fixed the problem we found in the transfers, caused by the _3001 Request not supported_. 
Please resume the testing and let us know if anything is still wrong.

Cheers,
Mihai

**Comment by simonmichal** [comment]
@mpatrascoiu : thanks a lot!

**Comment by paulmillar** [comment]
ESCAPE routine xroot-TPC testing, which uses the FTS3-Pilot instance, is now passing with dCache destinations.

**Comment by simonmichal** [comment]
Can we close this issue?

**Comment by paulmillar** [comment]
I would say "yes", please close this issue.  Unfortunately, I can't do that myself.
