### ISSUE TITLE
gsi el7 clients fail to connect to alma9 MGM

### ISSUE THREAD

**Issue by adriansev** [xrootd/xrootd#2014]
It seems that there is a client-side openssl problem when the connecting client is on Centos7 and the server is Alma9 (in my case an EOS Alma9 MGM).
The same connection with the same client (5.5.5 at this moment) from a Fedora38 works without problem.
The gsi debug output for both cases can be inspected here: https://asevcenc.web.cern.ch/asevcenc/gsi_dump/

Looking at the code it seems that the problem at this point:
https://github.com/xrootd/xrootd/blob/master/src/XrdSecgsi/XrdSecProtocolgsi.cc#L3320
(so everything else up to this point is ok)

but i'm not sure is the implementation of Cipher method is this one:
https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptosslCipher.cc#L241
and what could be the problem.

Let me know if i can enable tracing options and provide more logging.
Thanks a lot!

**Comment by mike-leech** [comment]
We are seeing exactly the same problem. Client Centos7(xrootd5.5.4-1) server Alma9(xrootd5.5.5-1) .

update-crypto-policies --set DEFAULT:SHA1 on server and restarting has no effect.

xrdcp from Alma 9 client to Alma 9 server works fine.

[leech@pplxint11 ~]$ xrdcp -f -d1 xroot://pplxwn021//tmp/zap local_zap2
230525 11:37:45 255389 secgsi_ClientDoCert: could not instantiate session cipher using cipher public info from server
[2023-05-25 11:37:45.619578 +0100][Error  ][XRootDTransport   ] [pplxwn021:1094.0] Auth protocol handler for gsi refuses to give us more credentials Secgsi: ErrParseBuffer: could not instantiate session cipher : kXGS_cert
[2023-05-25 11:37:45.619725 +0100][Error  ][AsyncSock         ] [pplxwn021:1094.0] Socket error while handshaking: [FATAL] Auth failed
[2023-05-25 11:37:45.619845 +0100][Error  ][PostMaster        ] [pplxwn021:1094] elapsed = 1, pConnectionWindow = 120 seconds.
[2023-05-25 11:37:45.619895 +0100][Error  ][PostMaster        ] [pplxwn021:1094] Unable to recover: [FATAL] Auth failed.
[2023-05-25 11:37:45.619932 +0100][Error  ][XRootD            ] [pplxwn021:1094] Impossible to send message kXR_open (file: /tmp/zap, mode: 00, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
[0B/0B][100%][==================================================][0B/s]  
Run: [FATAL] Auth failed: Secgsi: ErrParseBuffer: could not instantiate session cipher : kXGS_cert (source)


I'm also willing to test, as this is stalling our upgrade of all systems to Alma 9.

Just a thought. Major upgrade to openssl3 on EL9. Lots of legacy stuff has been dropped.

Cheers.

**Comment by abh3** [comment]
This discusses some additional things you may need o do

https://computingforgeeks.com/configure-system-wide-cryptographic-policies/

However, while this should work for RH distribution. It's not at all clear 
crypto policies will work in the Alma distribution; at least not without 
somme additional effort.

Andy

**Comment by adriansev** [comment]
@abh3 Alma and RH are the same distro technically and as i said i have
```
[root@seau2 ~]# update-crypto-policies --show
LEGACY:1024BITS:SHA1
```
so all possible lowest requirements

**Comment by amadio** [comment]
What about doing the reverse, that is, setting the policy to "FUTURE" on the client side?

**Comment by adriansev** [comment]
centos7 does not have update-crypto-policies nor crypto-policies..

**Comment by mike-leech** [comment]
I've also tried enabling the openssl legacy provider directly on the server. Still no luck I'm afraid.

[root@p ~]# update-crypto-policies --show
LEGACY:SHA1
[root@p ~]# openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.0.7
    status: active
  legacy
    name: OpenSSL Legacy Provider
    version: 3.0.7
    status: active

**Comment by abh3** [comment]
Well, technically sort of. Alma is not based on any release that Redhat 
creates. So, it can be, in some repsects, very different. The whole 
crypto scheme was also invented by Redhat and I am skeptical that Alma 
faithfully duplicates it.

That said, there are several issues with the "future" x509 requirements 
with respect to backward compatability. SHA1 is only one of them. To 
capture all the conflict yous should be setting the default to "legacy" 
which (at least in Redhat) adjust all the conflicts. So use

update-crypto-policies --set LEGACY

Now whether that works in Alma is a different question.

**Comment by adriansev** [comment]
Hi @abh3 so, Alma is a Redhat clone as Centos was for EL7 .. also, see their statement:
`AlmaLinux OS is a 1:1 binary compatible clone of RHEL® guided and built by the community.`
So, technically RedHat Enterprise Linux, Alma Linux and Rocky Linux are the same thing.
As for the crypto policies, see above where i shown what i have:
```
[root@seau2 ~]# update-crypto-policies --show
LEGACY:1024BITS:SHA1
```

**Comment by Clarky-Bear** [comment]
Hi, we're seeing the same issue at Durham. We have C7, R9 gateways running xroot-1:5.5.4 and receive cipher issues between C7 to R9 communication even with legacy ciphers turned on. We're finding R8 to be a good middle man between the two but it means we're running a third gateway to permit cross communication.

**Comment by bbockelm** [comment]
Why are we looking at SHA-1 stuff?

The error message refers to the failure of a session cipher.  In the case of a RHEL7, it is exchanged via 512 bit DH, no?

**Comment by bbockelm** [comment]
Hi Adrian,

For crypto policies, I believe the minimum Diffie Hellman is 2048 (unless `FUTURE` is selected; in that case, it's 3072).  Can you try that size?

Thanks,

Brian

**Comment by adriansev** [comment]
Hi @bbockelm erm, why would i increase something when the need is to lower everything down until the EL7 client works? the target is an Alma9 EOS MGM and the client is a Centos7 (and this is actually the problem, as a fedora 38 client works without problem)

**Comment by bbockelm** [comment]
@adriansev - I'm not suggesting it's a solution, just want to test the theory that this is where the problem is.  It would be very useful to understand it's indeed in the DH settings and not elsewhere in the code.

(Memory is very hazy of my last read of this code but I believe the DH key itself is later on truncated so there's only 512 bits of security even if the buffers fed to OpenSSL are 2048 bit.... i.e., there's no effective security here unless you're using `xroots`.  So the setting of the DH size can be made to "whatever makes OpenSSL happy")

**Comment by adriansev** [comment]
@bbockelm yeah, i did not get it but make sense. so i did as you suggested, rebooted the machine and the error is the same. for reference the overall current policy looks like this: https://asevcenc.web.cern.ch/asevcenc/eos_config_auger/new_pol

**Comment by abh3** [comment]
Let's see here, the following RedHat article shows how you can display 
what the requirements are for each crypto policy using gnutls-utils and 
httpd/ Here we are interested in what the requirement are when you execute

update-crypto-policies --set LEGACY

Follow the server recipe in the article using alma 9. Then we can see 
where EL7 is diverging from what alma 9 wants.

See: https://access.redhat.com/articles/3666211

According to RH, LEGACY should  ensures maximum compatibility with Red 
Hat Enterprise Linux 5 and earlier; it is less secure due to an 
increased attack surface. In addition to the DEFAULT level algorithms and 
protocols, it includes support for the TLS 1.0 and 1.1 protocols. The 
algorithms DSA, 3DES, and RC4 are allowed, while RSA keys and 
Diffie-Hellman parameters are accepted if they are at least 1023 bits 
long.

This may not be the case in Alma 9 so let's find out.

Andy

**Comment by adriansev** [comment]
Hi @abh3 see the link posted above: https://asevcenc.web.cern.ch/asevcenc/eos_config_auger/new_pol
which is the full state of current crypto policy on the server.

Is built with SHA1 on top of LEGACY after which i added this pmod (well the dh is now 2048):
```
min_dh_size = 512
min_dsa_size = 1024
min_rsa_size = 1024
```

the end result the is policy dump reference above
EL7/Centos7 have no crypto policy AFAIK so i have no idea how to compare them.
(also, just to stress again: Alma9 _IS_ RHEL9 software/binary wise)
Also, the target MGM have the ops and dteam VOs configured so anyone registered with these VOs can do the testing from various clients.

**Comment by abh3** [comment]
Could you

export XrdSecDEBUG=1

and try connecting again and post the log output. It may tell us what the server really expects.

**Comment by xrootd-dev** [comment]
Oh never mind. I see you did that already.

**Comment by abh3** [comment]
Ah, could you post the OpenSSL versions of the centos7, fedora38, and Allma9 machines?

**Comment by adriansev** [comment]
EL7: 1.0.2k
Alma9: 3.0.7
Fedora38: 3.0.8

**Comment by VipulDavda** [comment]
Just to add, it works when connecting from Rocky8 client (openssl v1.1.1k).

**Comment by abh3** [comment]
Oh, yes, the majority talk here is about API compatability which I know is 
problematic. What we are talking about here is wire compatability. That is 
also questionable given the large changes in 3.0. Ine could convince 
oneself that this is the key issue since it works with fedora38 which is 
in the same release series but fails for 1.0.2. Any chance you would try 
the same test with 1.1.1?

**Comment by VipulDavda** [comment]
BTW, to try to make it work, we even changed the openssl config on Alma9  - https://www.practicalnetworking.net/practical-tls/openssl-3-and-legacy-providers/

**Comment by VipulDavda** [comment]
Re: upgrade EL7 to use openssl 1.1.1 

I'm new to xrootd but don't you have to compile xrootd to use openssl 1.1.1 on EL7? 

ldd /usr/bin/xrdcp
...
libssl.so.10 => /lib64/libssl.so.10 (0x00007fb857cbb000)
..
...
rpm -qf /lib64/libssl.so.10
openssl-libs-1.0.2k-26.el7_9.x86_64

**Comment by adriansev** [comment]
> Thanks for that observation. So, it might be that 1.0.1 is simply not compatible with 3.0. OK, so can you upbgrade your EL7 machine to 1.1.1 and change nothing else and see if it works?

Actually i do have openssl11 installed from epel:
```
openssl11-1.1.1k-5.el7.x86_64
openssl11-static-1.1.1k-5.el7.x86_64
openssl11-devel-1.1.1k-5.el7.x86_64
openssl11-libs-1.1.1k-5.el7.x86_64
```

but the epel provided xrootd is build with system openssl not with epel openssl
so, all i need is an xrootd rpm build with epel openssl11
and subsequently the gfal should be rebuild upon this new xrootd and openssl11

@amadio is there a possibility of a test rpm for EL7 that requires and use openssl11?

If this works, then the next EL7 xrootd release should work but the gfal packager for epel should also be contacted to repackage gfal on the new dependencies.

**Comment by amadio** [comment]
Sure, I will create RPMs using OpenSSL 1.1 from epel for testing. I will add a comment here when they are ready.

**Comment by bbockelm** [comment]
I think I figured it out.  The problem is this one:

https://github.com/openssl/openssl/issues/9792

Basically, in 2019 OpenSSL overhauled it's DH parameter generation code which resulted in it generating new DH parameters sent by the server that older clients did not like.  It appears the more lenient client-side check was kept but eventually the server-side change was reverted during 1.1.1 -- but based on some GDB footwork, it's back in 3.0.0.

Now, options:

1.  Backport the more lenient client side check and copy/paste it into the XRootD source code.  All prior versions of clients are still broken but newer ones on RHEL7 would work.  I assume this "break everything" is not an option.
2.  Select a fixed DH group, compatible with the old client and new, and hardcode it into the server side to always be used.

I think (2) is the more viable option; hardcoding a known good group is a fairly common solution (see https://wiki.openssl.org/index.php/Diffie-Hellman_parameters).

Unfortunately, XRootD's 512-bit DH is weak enough to not be considered secure by the 1990's; therefore, there's no standardized 512-bit DH group that we can easily reuse.  Instead, I'd just suggest generating any old one by hand and hardcode that.  Here's an example:
```
$ openssl dhparam 512 -5
Generating DH parameters, 512 bit long safe prime, generator 5
This is going to take a long time
......................................+..+...................+..+...+.............+......+................+.............+................................................................................+................................................................................+....+...........+...+.............+................+............................................................+...+.........+.............+.........+......+..............................................+....+..............+.................................................+..................+......+..............................+..+..+..........+.............+...........................+....+...+......+................+...+.+....+................+....................................+....+.+................................+............................................+..................+.............+............................................................+................++*++*++*++*++*++*
-----BEGIN DH PARAMETERS-----
MEYCQQDuCROhiIMH6R+BJGDf4OP5SlHM4pYjaODCuO02D8H9FwKopHU0T7XmOHZ7
eUxajA3EqUMqa5AY1+EzFV0JXpEfAgEF
-----END DH PARAMETERS-----
```

Loading that on the server side would replace the generation code:

https://github.com/xrootd/xrootd/blob/master/src/XrdCrypto/XrdCryptosslCipher.cc#L507-L518

For other sizes of DH parameters, one could simply do a lookup table.  RFC 3526 covers examples up through 4096.

**Comment by amadio** [comment]
I have put CentOS 7 RPMs linking against OpenSSL 1.1 from EPEL here:
https://xrootd.cern.ch/repo/centos/7/openssl11

The file with the repository configuration is here:
https://xrootd.cern.ch/xrootd-openssl11.repo

This repository is temporary, just for testing, it may be removed after this is tested.

**Comment by amadio** [comment]
@adriansev Could you please try to connect with the client above? For convenience:

```
$ podman run --rm -it centos:7
$ yum install -y epel-release && yum update -y
$ curl -L http://xrootd.cern.ch/xrootd-openssl11.repo > /etc/yum.repos.d/xrootd-openssl11.repo
$ cat /etc/yum.repos.d/xrootd-openssl11.repo
$ yum update
$ yum install xrootd-* # check that it installs xrootd-*5.5.5-1.el7.openssl1.1
$ xrdcp --version
$ ldd /usr/lib64/libXrdCrypto.so # (links against libssl.so.1.1)
```

Cheers,

**Comment by amadio** [comment]
I've tested the client linked against OpenSSL 1.1 and it works against the unpatched server. I also tested a server with this patch on Alma 9 with a client on lxplus7 and it also works.

**Comment by abh3** [comment]
OK, I merged this. However, could you rerun your test on the latest merge as @bbockelm made some last minute changes. I don't see how they will affect the test but you never know.

**Comment by adriansev** [comment]
@amadio I apologize for the silence, returning from holiday was a little bit busy.
So, as i said, i had to reinstall the machine to Centos 7 because of the pressure to be put in production BUT the problem still persist!!!
i installed the xrootd provided by you and the problem is still present despite that now the server is a standard centos 7!!! the logs with the new xrootd to the new installation are here: https://asevcenc.web.cern.ch/asevcenc/eos_config_auger/from_cent7/
Moreover, even on fedora i get the same message!
Thanks a lot for help!!!

**Comment by bbockelm** [comment]
Hi @adriansev -

What you post appears to be a different problem:

> Auth protocol handler for gsi refuses to give us more credentials Secgsi: ErrParseBuffer: could not instantiate digest object: kXGS_cert

The "digest" object here is used to sign messages.  Looking at the code, it defaults to `sha1:md5` (probably both are not enabled in your client if it's Fedora/RHEL9-based).  I believe the default digest can be set on the server side with:

```
sec.protocol gsi [...other opts...] -md:sha256
```

(ref: https://xrootd.slac.stanford.edu/doc/dev56/sec_config.htm)

If that doesn't solve it, let's file a separate ticket as it's a distinct issue.

Brian

**Comment by adriansev** [comment]
@bbockelm oh, yes, sorry for the noise, as soon as i put `-md:sha256:sha1:md5` it worked
Thanks a lot!!
