### ISSUE TITLE
XrdSciTokens config to refuse tokens without scopes

### ISSUE THREAD

**Issue by esindril** [xrootd/xrootd#2121]
Having enabled tokens for both xroot and http for the EOS instance in Vienna, a couple of tests in the CMS SAM/ETF testsuite were failing due to the assumption that the scitokens library would refuse tokens without any scopes. This apparently is not the case. Therefore, could this be added as an option to the scitokens configuration. According to @bbockelm, there might already be some option in place to achieve this. If so, please share it with us so that we can pass this info to service manages to properly configure their instances. 

Please keep in mind that such instances also use the scitokens_mapfile.json option to configure certain mappings for paths - a thing which might influence the scitokens ability to refuse tokens without any scopes.

Thanks!

**Comment by bbockelm** [comment]
@esindril - this is the approach I was working on while flying back over the Atlantic: #2122

Note the current code considers an explicit mapping in the mapfile as an alternate authorization.  If you can post the details of what's needed in Vienna (and why they are explicitly mapping), I might be able to come up with an approach in the current code base.

Otherwise, the current behavior is equivalent to:

```
authorization_strategy = capability group mapping
```

and I think you're asking for:

```
authorization_strategy = capability group
```

**Comment by stlammel** [comment]
Just realized, we maybe talking about different mappings here. An access mapping based on token subject i agree falls into the same authorizing access. A mapping to a local user is what i was thinking when writing the above.
 - Stephan

**Comment by esindril** [comment]
Hi Brian,

I think there are more nitty-gritty details to be ironed out when it comes to the interplay of the different so-called authorization strategies. But for this particular case, I think a simple `fail-no-scope-tokens=[false]` option that can be turned on in the config, that would simply refuse non-scoped tokens off the bat would be good enough.

Thanks!

**Comment by esindril** [comment]
Hi all,

After looking at this with @amadio, I need to refine actually the initial observation. What I believe CMS wants and @stlammel please correct me if I am wrong, is that the authz library would refuse tokens without the `storage./read/write` scope. My initial comment that the authz library should refuse tokens without `scope` is actually already in place and works as expected. Therefore, @bbockelm how can we achieve this desired behavior?

Just for completeness, a CMS token that is expected to fail the scitokens authz checks, looks like this:

```
{
  "wlcg.ver": "1.0",
  "sub": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
  "aud": "https://wlcg.cern.ch/jwt/v1/any",
  "nbf": 1701698621,
  "scope": "openid compute.create offline_access profile compute.read compute.cancel compute.modify",
  "iss": "https://cms-auth.web.cern.ch/",
  "exp": 1702130621,
  "iat": 1701698621,
  "jti": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
  "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

Thanks!

**Comment by abh3** [comment]
This appears to be the question of the day! The same issue seems to be in 
dCache as well. The topic is trending!

Andy

**Comment by stlammel** [comment]
dCache allowed storage access with a compute (and no storage) scope initially but this was addressed by developers several months ago.
 - Stephan

**Comment by abh3** [comment]
Indeed, it would suggest that the issue is in the SciToken library. 
However, it's still worth ruling out ztn as the driver.

**Comment by amadio** [comment]
As far as I understand, tokens without scope were already rejected by scitokens, as commented by Elvin above, and although there were some bugs which were fixed by #2132 and #2152, rejecting tokens without `storage.{read,write}` scopes does not seem to have been part of these fixes. @bbockelm Could you please take a look at what is still missing, so we can add all token-related fixes into the next release? Thank you!

**Comment by bbockelm** [comment]
Hi @amadio - 

The approach to solving this is in #2122; I had a comment along those lines in that ticket but apparently failed to hit the "submit" button after I wrote it.  Unfortunately, it's going to be a new configuration option given it's a change in default behavior and different groups have asked for different behavior.

I plan to finish up the work started #2122 this week and post a fresh PR.

Brian

**Comment by amadio** [comment]
Ok, thank you @bbockelm. I will wait for the new pull request then. However, a new configuration option needs to wait until 5.7, I cannot release it in a patch release. Cheers,

**Comment by abh3** [comment]
Also, @bbockelm please send/post the text/explanation of the new option well ahead of time so we can put it into the documentation pipeline.

**Comment by amadio** [comment]
I think that with #2205 and #2176 now both merged, this can finally be closed. There are still some things that could work better on the scitokens side, but we can address that in the future. For now, XRootD 5.7 will be ready to be configured to satisfy all use cases from this issue.
